SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;

--
-- Base de données : Projet_JO_2024
--

--
-- Structure de la table Athlete
--

DROP TABLE IF EXISTS Athlete;
CREATE TABLE Athlete (
  id_athlete int(11) PRIMARY KEY AUTO_INCREMENT,
  firstname_athlete VARCHAR(50) NOT NULL,
  name_athlete VARCHAR(50) NOT NULL,
  birthday_athlete date DEFAULT NULL,
  gender_athlete enum('MAN', 'WOMAN') NOT NULL,
  code_country char(3) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table Country
--

DROP TABLE IF EXISTS Country;
CREATE TABLE Country (
  code_country char(3) NOT NULL PRIMARY KEY,
  name_country VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table Date_calendar
--

DROP TABLE IF EXISTS Date_calendar;
CREATE TABLE Date_calendar (
  id_date_cal int(11) PRIMARY KEY AUTO_INCREMENT,
  date_cal date NOT NULL,
  medal_ceremony_date_cal tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table Discipline
--

DROP TABLE IF EXISTS Discipline;
CREATE TABLE Discipline (
  id_disc int(11) PRIMARY KEY AUTO_INCREMENT,
  name_fr_disc VARCHAR(50) NOT NULL,
  name_an_disc VARCHAR(50),
  category_disc enum('OLYMPIC', 'PARALYMPIC') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table Event
--

DROP TABLE IF EXISTS Event;
CREATE TABLE Event (
  id_event int(11) PRIMARY KEY AUTO_INCREMENT,
  name_event VARCHAR(50) NOT NULL,
  format_event enum('INDIVIDUAL', 'COLLECTIVE', 'HYBRIDE') NOT NULL,
  gender_event enum('MAN', 'WOMAN', 'MIXED') NOT NULL,
  id_disc int(11) NOT NULL,
  id_record int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table Medal
--

DROP TABLE IF EXISTS Medal;
CREATE TABLE Medal (
  id_medal int(11) PRIMARY KEY AUTO_INCREMENT,
  type_medal enum('GOLD','SILVER','BRONZE') NOT NULL,
  id_event int(11) NOT NULL,
  id_athlete int(11) DEFAULT NULL,
  id_date_cal int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table Record
--

DROP TABLE IF EXISTS Record;
CREATE TABLE Record (
  id_record int(11) PRIMARY KEY AUTO_INCREMENT,
  stat_record VARCHAR(32) NOT NULL,
  date_record date,
  id_event int(11) DEFAULT NULL,
  id_athlete int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table Transport
--

DROP TABLE IF EXISTS Transport;
CREATE TABLE Transport (
  id_trans int(11) PRIMARY KEY AUTO_INCREMENT,
  name_trans enum('TRAIN', 'TRAMWAY', 'BUS', 'METRO') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table Site
--

DROP TABLE IF EXISTS Site;
CREATE TABLE Site (
  id_site int(11) PRIMARY KEY AUTO_INCREMENT,
  name_site VARCHAR(50) NOT NULL,
  adress_site VARCHAR(50) NOT NULL,
  creation_date_site date DEFAULT NULL,
  capacity_site int(11) DEFAULT NULL,
  URL_site VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table Team
--

DROP TABLE IF EXISTS Team;
CREATE TABLE Team (
  id_team int(11) PRIMARY KEY AUTO_INCREMENT,
  size_team int(11) NOT NULL,
  gender_team enum('MAN', 'WOMAN', 'MIXED') NOT NULL,
  code_country char(3) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table Is_from
--

DROP TABLE IF EXISTS Is_from;
CREATE TABLE Is_from (
  id_athlete int(11) NOT NULL,
  code_country char(3) NOT NULL,
  PRIMARY KEY (id_athlete, code_country)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table To_pertain_team
--

DROP TABLE IF EXISTS To_pertain_team;
CREATE TABLE To_pertain_team (
  id_athlete int(11) NOT NULL,
  id_team int(11) NOT NULL,
  PRIMARY KEY (id_athlete, id_team)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table To_Register_athlete
--

DROP TABLE IF EXISTS To_Register_athlete;
CREATE TABLE To_Register_athlete (
  id_event int(11) NOT NULL,
  id_athlete int(11) NOT NULL,
  PRIMARY KEY (id_event, id_athlete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table To_Register_team
--

DROP TABLE IF EXISTS To_Register_team;
CREATE TABLE To_Register_team (
  id_event int(11) NOT NULL,
  id_team int(11) NOT NULL,
  PRIMARY KEY (id_event, id_team)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table To_Schedule
--

DROP TABLE IF EXISTS To_Schedule;
CREATE TABLE To_Schedule (
  id_site int(11) NOT NULL,
  id_date_cal int(11) NOT NULL,
  id_event int(11) NOT NULL,
  PRIMARY KEY (id_site, id_date_cal, id_event)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Structure de la table To_Serve
--

DROP TABLE IF EXISTS To_Serve;
CREATE TABLE To_Serve (
  id_site int(11) NOT NULL,
  id_trans int(11) NOT NULL,
  num_ligne VARCHAR(50) NOT NULL,
  station_name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id_site, id_trans)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



--
-- Index et Contraintes pour la table Athlete
--
ALTER TABLE Athlete
  ADD INDEX IDX_Athlete_code_country (code_country),

  ADD CONSTRAINT FK_Athlete_code_country FOREIGN KEY (code_country) REFERENCES Country (code_country) ON DELETE SET NULL;

--
-- Index et Contraintes pour la table Event
--
ALTER TABLE Event
  ADD INDEX IDX_Event_id_disc (id_disc),
  ADD INDEX IDX_Event_id_record (id_record),

  ADD CONSTRAINT FK_Event_id_disc FOREIGN KEY (id_disc) REFERENCES Discipline (id_disc) ON DELETE CASCADE,
  ADD CONSTRAINT FK_Event_id_record FOREIGN KEY (id_record) REFERENCES Record (id_record) ON DELETE SET NULL;

--
-- Index et Contraintes pour la table Medal
--
ALTER TABLE Medal
  ADD INDEX IDX_Medal_id_event (id_event),
  ADD INDEX IDX_Medal_id_athlete (id_athlete),
  ADD INDEX IDX_Medal_id_date_cal (id_date_cal),

  ADD CONSTRAINT FK_Medal_id_event FOREIGN KEY (id_event) REFERENCES Event (id_event) ON DELETE CASCADE,
  ADD CONSTRAINT FK_Medal_id_athlete FOREIGN KEY (id_athlete) REFERENCES Athlete (id_athlete) ON DELETE SET NULL,
  ADD CONSTRAINT FK_Medal_id_date_cal FOREIGN KEY (id_date_cal) REFERENCES Date_calendar (id_date_cal) ON DELETE SET NULL;

--
-- Indexet Contraintes pour la table Record
--
ALTER TABLE Record
  ADD INDEX IDX_Record_id_event (id_event),
  ADD INDEX IDX_Record_id_athlete (id_athlete),

  ADD CONSTRAINT FK_Record_id_event FOREIGN KEY (id_event) REFERENCES Event (id_event) ON DELETE CASCADE,
  ADD CONSTRAINT FK_Record_id_athlete FOREIGN KEY (id_athlete) REFERENCES Athlete (id_athlete) ON DELETE SET NULL;

--
-- Index pour la table Team et Contraintes pour la table Team
--
ALTER TABLE Team
  ADD INDEX IDX_Team_code_country (code_country),

  ADD CONSTRAINT FK_Team_code_country FOREIGN KEY (code_country) REFERENCES Country (code_country) ON DELETE SET NULL;

--
-- Index et Contraintes pour la table Is_from
--
ALTER TABLE Is_from
  -- ADD INDEX IDX_Is_from_id_athlete (id_athlete),
  -- ADD INDEX IDX_Is_from_code_country (code_country),

  ADD CONSTRAINT FK_Is_from_id_athlete FOREIGN KEY (id_athlete) REFERENCES Athlete (id_athlete) ON DELETE CASCADE,
  ADD CONSTRAINT FK_Is_from_code_country FOREIGN KEY (code_country) REFERENCES Country (code_country) ON DELETE CASCADE;

--
-- Index et Contraintes pour la table To_pertain_team
--
ALTER TABLE To_pertain_team
  -- ADD INDEX IDX_To_pertain_team_id_team (id_team),
  -- ADD INDEX IDX_To_pertain_team_id_athlete (id_athlete),

  ADD CONSTRAINT FK_To_pertain_team_id_athlete FOREIGN KEY (id_athlete) REFERENCES Athlete (id_athlete) ON DELETE CASCADE,
  ADD CONSTRAINT FK_To_pertain_team_id_team FOREIGN KEY (id_team) REFERENCES Team (id_team) ON DELETE CASCADE;

--
-- Index et Contraintes pour la table To_Register_athlete
--
ALTER TABLE To_Register_athlete
  -- ADD INDEX IDX_To_Register_athlete_id_athlete (id_athlete),
  -- ADD INDEX IDX_To_Register_athlete_id_event (id_event),

  ADD CONSTRAINT FK_To_Register_athlete_id_athlete FOREIGN KEY (id_athlete) REFERENCES Athlete (id_athlete) ON DELETE CASCADE,
  ADD CONSTRAINT FK_To_Register_athlete_id_event FOREIGN KEY (id_event) REFERENCES Event (id_event) ON DELETE CASCADE;

--
-- Index et Contraintes pour la table To_Register_team
--
ALTER TABLE To_Register_team
  -- ADD INDEX IDX_To_Register_team_id_team (id_team),
  -- ADD INDEX IDX_To_Register_team_id_event (id_event),

  ADD CONSTRAINT FK_To_Register_team_id_event FOREIGN KEY (id_event) REFERENCES Event (id_event) ON DELETE CASCADE,
  ADD CONSTRAINT FK_To_Register_team_id_team FOREIGN KEY (id_team) REFERENCES Team (id_team) ON DELETE CASCADE;

--
-- Index et Contraintes pour la table To_Schedule
--
ALTER TABLE To_Schedule
  -- ADD INDEX IDX_To_Schedule_id_date_cal (id_date_cal),
  -- ADD INDEX IDX_To_Schedule_id_event (id_event),
  -- ADD INDEX IDX_To_Schedule_id_site (id_site),

  ADD CONSTRAINT FK_To_Schedule_id_date_cal FOREIGN KEY (id_date_cal) REFERENCES Date_calendar (id_date_cal) ON DELETE CASCADE,
  ADD CONSTRAINT FK_To_Schedule_id_event FOREIGN KEY (id_event) REFERENCES Event (id_event) ON DELETE CASCADE,
  ADD CONSTRAINT FK_To_Schedule_id_site FOREIGN KEY (id_site) REFERENCES Site (id_site) ON DELETE CASCADE;

--
-- Index et Contraintes pour la table To_Serve
--
ALTER TABLE To_Serve
  -- ADD INDEX IDX_To_Serve_id_trans (id_trans),
  -- ADD INDEX IDX_To_Serve_id_site (id_site),

  ADD CONSTRAINT FK_To_Serve_id_site FOREIGN KEY (id_site) REFERENCES Site (id_site) ON DELETE CASCADE,
  ADD CONSTRAINT FK_To_Serve_id_trans FOREIGN KEY (id_trans) REFERENCES Transport (id_trans) ON DELETE CASCADE;

COMMIT;
INSERT IGNORE INTO Transport (name_trans) VALUES
('TRAIN'),
('TRAMWAY'),
('BUS'),
('METRO');

INSERT IGNORE INTO Site (name_site, adress_site, creation_date_site, capacity_site, URL_site) VALUES
 ('Seine', 'Seine', NULL, 600000, 'https://fr.wikipedia.org//wiki/Seine_%C3%A0_Paris'),
 ('Stade de France', 'ZAC du Cornillon Nord93200 Saint-Denis,  France', '1995-00-00', 77083, 'https://fr.wikipedia.org//wiki/Stade_de_France'),
 ('Village olympique de Saint-Denis', 'Village olympique de Saint-Denis', NULL, NULL, 'https://fr.wikipedia.org//wiki/Village_olympique_de_Saint-Denis'),
 ('Centre aquatique', 'Avenue du Président-Wilson, Saint-Denis', '2024-00-00', 5000, 'https://fr.wikipedia.org//wiki/Piscine_olympique_de_Saint-Denis'),
 ('Stade Tour Eiffel(Champ-de-Mars)', 'Stade Tour Eiffel(Champ-de-Mars)', '1770-00-00', 12860, 'https://fr.wikipedia.org//wiki/Champ-de-Mars_(Paris)'),
 ('Pont Alexandre-III et Seine (nage)', 'Pont Alexandre-III et Seine (nage)', NULL, 1000, 'https://fr.wikipedia.org//wiki/Pont_Alexandre-III'),
 ('Grand Palais', 'Grand Palais', '1900-00-00', 8000, 'https://fr.wikipedia.org//wiki/Grand_Palais_(Paris)'),
 ('Arena Champ-de-Mars(Grand Palais éphémère)', 'Arena Champ-de-Mars(Grand Palais éphémère)', '2021-06-12', 8356, 'https://fr.wikipedia.org//wiki/Grand_Palais_%C3%A9ph%C3%A9m%C3%A8re'),
 ('Esplanade des Invalides', 'Esplanade des Invalides', '1704-00-00', 8000, 'https://fr.wikipedia.org//wiki/Esplanade_des_Invalides'),
 ('Arena Paris Sud(Parc des expositions de la porte de Versailles)', '1 place de la Porte-de-Versailles  15e arrondissement de Paris, Paris France', NULL, 6650, 'https://fr.wikipedia.org//wiki/Paris_Expo_Porte_de_Versailles'),
 ('Parc des Princes', '24 rue du Commandant-Guilbaud 75016 Paris, France', '1967-07-08', 47926, 'https://fr.wikipedia.org//wiki/Parc_des_Princes'),
 ('Stade Roland-Garros', '3 avenue Gordon-Bennett  75016, France', '1928-00-00', 14962, 'https://fr.wikipedia.org//wiki/Stade_Roland-Garros'),
 ('Palais omnisports de Paris-Bercy', '8, boulevard de Bercy, Paris 12e', '1984-02-03', 15000, 'https://fr.wikipedia.org//wiki/Palais_omnisports_de_Paris-Bercy'),
 ('Arena Porte de la Chapelle', '58 boulevard Ney  18e arrondissement de Paris, Paris France', '2024-02-11', 7000, 'https://fr.wikipedia.org//wiki/Arena_Porte_de_la_Chapelle'),
 ('Paris La Défense Arena', '99 Jardins de l''ArcheNanterre France', '2013-12-02', 17000, 'https://fr.wikipedia.org//wiki/Paris_La_D%C3%A9fense_Arena'),
 ('Stade Yves-du-Manoir', '12, rue François-Faber92700 Colombes', '1907-00-00', 15000, 'https://fr.wikipedia.org//wiki/Stade_d%C3%A9partemental_Yves-du-Manoir'),
 ('Base nautique de Vaires-sur-Marne', 'Base nautique de Vaires-sur-Marne', '1980-00-00', 24000, 'https://fr.wikipedia.org//wiki/%C3%8Ele_de_loisirs_de_Vaires-Torcy'),
 ('Château de Versailles', 'Château de Versailles', NULL, 40000, 'https://fr.wikipedia.org//wiki/Ch%C3%A2teau_de_Versailles'),
 ('Vélodrome national', '1, rue Laurent FignonMontigny-le-Bretonneux', '2011-10-03', 5000, 'https://fr.wikipedia.org//wiki/V%C3%A9lodrome_de_Saint-Quentin-en-Yvelines'),
 ('Colline d''Élancourt', 'Colline d''Élancourt', NULL, 15000, 'https://fr.wikipedia.org//wiki/Colline_d%27%C3%89lancourt'),
 ('Golf national', 'Golf national', NULL, 32720, 'https://fr.wikipedia.org//wiki/Golf_national'),
 ('Marina olympique du Roucas-Blanc', '6 Prom. Georges Pompidou, 13008 Marseille', NULL, 12262, 'https://fr.wikipedia.org//wiki/Marina_olympique_du_Roucas-Blanc'),
 ('Teahupo''o', 'Teahupo''o', NULL, 600, 'https://fr.wikipedia.org//wiki/Teahupo%27o'),
 ('Stade de Bordeaux', 'Cours Jules-Ladoumègue 33300 Bordeaux, France', '2012-00-00', 42000, 'https://fr.wikipedia.org//wiki/Matmut_Atlantique'),
 ('Stade Pierre-Mauroy', '261 Boulevard de Tournai 59650 Villeneuve-d''Ascq, France', '2012-08-17', 27000, 'https://fr.wikipedia.org//wiki/Stade_Pierre-Mauroy'),
 ('Parc Olympique lyonnais', '10 avenue Simone-Veil 69150 Décines-Charpieu, France', '2012-10-22', 59186, 'https://fr.wikipedia.org//wiki/Parc_Olympique_lyonnais'),
 ('Stade Vélodrome', '3 boulevard Michelet 13008 Marseille, France', '1935-04-28', 67394, 'https://fr.wikipedia.org//wiki/Stade_V%C3%A9lodrome'),
 ('Stade de la Beaujoire', '5 boulevard de la Beaujoire 44300 Nantes', '1984-05-08', 37473, 'https://fr.wikipedia.org//wiki/Stade_de_la_Beaujoire'),
 ('Stade Riviera', 'Boulevard des Jardiniers06200 Nice  France', '2011-08-06', 36178, 'https://fr.wikipedia.org//wiki/Allianz_Riviera'),
 ('Stade Geoffroy-Guichard', '14, rue Paul et Pierre Guichard42000 Saint-Étienne', '1930-09-00', 41965, 'https://fr.wikipedia.org//wiki/Stade_Geoffroy-Guichard'),
 ('Site d''escalade du Bourget', '9 rue Roger Salengro, 93350, Le Bourget', '2020-00-00', 6000, 'https://fr.wikipedia.org//wiki/Site_d%27escalade_du_Bourget'),
 ('Parc des expositions du Bourget', 'Le Bourget, Seine-Saint-Denis, France', NULL, NULL, 'https://fr.wikipedia.org//wiki/Parc_des_expositions_de_Paris-Le_Bourget'),
 ('Place de la Concorde', 'Place de la Concorde', '1763-00-00', NULL, 'https://fr.wikipedia.org//wiki/Place_de_la_Concorde'),
 ('Arena Paris Nord', 'Villepinte, Seine-Saint-Denis France', '1982-12-00', 6000, 'https://fr.wikipedia.org//wiki/Parc_des_expositions_de_Paris-Nord_Villepinte'),
 ('Centre national de tir sportif', 'Route de Lignières, RD 925, 36130 Déols,  France', '2018-00-00', NULL, 'https://fr.wikipedia.org//wiki/Centre_national_de_tir_sportif');

INSERT IGNORE INTO Country (code_country, name_country) VALUES
('AFG', 'Afghanistan'),
('ZAF', 'Afrique du Sud'),
('ALA', 'Îles Åland'),
('ALB', 'Albanie'),
('DZA', 'Algérie'),
('DEU', 'Allemagne'),
('AND', 'Andorre'),
('AGO', 'Angola'),
('AIA', 'Anguilla'),
('ATA', 'Antarctique'),
('ATG', 'Antigua-et-Barbuda'),
('SAU', 'Arabie saoudite'),
('ARG', 'Argentine'),
('ARM', 'Arménie'),
('ABW', 'Aruba'),
('AUS', 'Australie'),
('AUT', 'Autriche'),
('AZE', 'Azerbaïdjan'),
('BHS', 'Bahamas'),
('BHR', 'Bahreïn'),
('BGD', 'Bangladesh'),
('BRB', 'Barbade'),
('BLR', 'Biélorussie'),
('BEL', 'Belgique'),
('BLZ', 'Belize'),
('BEN', 'Bénin'),
('BMU', 'Bermudes'),
('BTN', 'Bhoutan'),
('BOL', 'Bolivie'),
('BES', 'Pays-Bas caribéens'),
('BIH', 'Bosnie-Herzégovine'),
('BWA', 'Botswana'),
('BVT', 'Île Bouvet'),
('BRA', 'Brésil'),
('BRN', 'Brunei'),
('BGR', 'Bulgarie'),
('BFA', 'Burkina Faso'),
('BDI', 'Burundi'),
('CYM', 'Îles Caïmans'),
('KHM', 'Cambodge'),
('CMR', 'Cameroun'),
('CAN', 'Canada'),
('CPV', 'Cap-Vert'),
('CAF', 'République centrafricaine'),
('CHL', 'Chili'),
('CHN', 'Chine'),
('CXR', 'Île Christmas'),
('CYP', 'Chypre'),
('CCK', 'Îles Cocos'),
('COL', 'Colombie'),
('COM', 'Comores'),
('COG', 'République du Congo'),
('COD', 'République démocratique du Congo'),
('COK', 'Îles Cook'),
('KOR', 'Corée du Sud'),
('PRK', 'Corée du Nord'),
('CRI', 'Costa Rica'),
('CIV', 'Côte d''Ivoire'),
('HRV', 'Croatie'),
('CUB', 'Cuba'),
('CUW', 'Curaçao'),
('DNK', 'Danemark'),
('DJI', 'Djibouti'),
('DOM', 'République dominicaine'),
('DMA', 'Dominique'),
('EGY', 'Égypte'),
('ARE', 'Émirats arabes unis'),
('ECU', 'Équateur'),
('ERI', 'Érythrée'),
('ESP', 'Espagne'),
('EST', 'Estonie'),
('USA', 'États-Unis'),
('ETH', 'Éthiopie'),
('FLK', 'Malouines'),
('FRO', 'Îles Féroé'),
('FJI', 'Fidji'),
('FIN', 'Finlande'),
('FRA', 'France'),
('GAB', 'Gabon'),
('GMB', 'Gambie'),
('GEO', 'Géorgie'),
('SGS', 'Géorgie du Sud-et-les îles Sandwich du Sud'),
('GHA', 'Ghana'),
('GIB', 'Gibraltar'),
('GRC', 'Grèce'),
('GRD', 'Grenade'),
('GRL', 'Groenland'),
('GLP', 'Guadeloupe'),
('GUM', 'Guam'),
('GTM', 'Guatemala'),
('GGY', 'Guernesey'),
('GIN', 'Guinée'),
('GNB', 'Guinée-Bissau'),
('GNQ', 'Guinée équatoriale'),
('GUY', 'Guyana'),
('GUF', 'Guyane'),
('HTI', 'Haïti'),
('HMD', 'Îles Heard-et-MacDonald'),
('HND', 'Honduras'),
('HKG', 'Hong Kong'),
('HUN', 'Hongrie'),
('UMI', 'Îles mineures éloignées des États-Unis'),
('IND', 'Inde'),
('IDN', 'Indonésie'),
('IRN', 'Iran'),
('IRQ', 'Irak'),
('IRL', 'Irlande'),
('ISL', 'Islande'),
('ISR', 'Israël'),
('ITA', 'Italie'),
('JAM', 'Jamaïque'),
('JPN', 'Japon'),
('JEY', 'Jersey'),
('JOR', 'Jordanie'),
('KAZ', 'Kazakhstan'),
('KEN', 'Kenya'),
('KGZ', 'Kirghizistan'),
('KIR', 'Kiribati'),
('KWT', 'Koweït'),
('LAO', 'Laos'),
('LSO', 'Lesotho'),
('LVA', 'Lettonie'),
('LBN', 'Liban'),
('LBR', 'Liberia'),
('LBY', 'Libye'),
('LIE', 'Liechtenstein'),
('LTU', 'Lituanie'),
('LUX', 'Luxembourg'),
('MAC', 'Macao'),
('MKD', 'Macédoine du Nord'),
('MDG', 'Madagascar'),
('MYS', 'Malaisie'),
('MWI', 'Malawi'),
('MDV', 'Maldives'),
('MLI', 'Mali'),
('MLT', 'Malte'),
('IMN', 'Île de Man'),
('MNP', 'Îles Mariannes du Nord'),
('MAR', 'Maroc'),
('MHL', 'Îles Marshall'),
('MTQ', 'Martinique'),
('MUS', 'Maurice'),
('MRT', 'Mauritanie'),
('MYT', 'Mayotte'),
('MEX', 'Mexique'),
('FSM', 'États fédérés de Micronésie'),
('MDA', 'Moldavie'),
('MCO', 'Monaco'),
('MNG', 'Mongolie'),
('MNE', 'Monténégro'),
('MSR', 'Montserrat'),
('MOZ', 'Mozambique'),
('MMR', 'Birmanie'),
('NAM', 'Namibie'),
('NRU', 'Nauru'),
('NPL', 'Népal'),
('NIC', 'Nicaragua'),
('NER', 'Niger'),
('NGA', 'Nigeria'),
('NIU', 'Niue'),
('NFK', 'Île Norfolk'),
('NOR', 'Norvège'),
('NCL', 'Nouvelle-Calédonie'),
('NZL', 'Nouvelle-Zélande'),
('IOT', 'Territoire britannique de l''océan Indien'),
('OMN', 'Oman'),
('UGA', 'Ouganda'),
('UZB', 'Ouzbékistan'),
('PAK', 'Pakistan'),
('PLW', 'Palaos'),
('PSE', 'Palestine'),
('PAN', 'Panama'),
('PNG', 'Papouasie-Nouvelle-Guinée'),
('PRY', 'Paraguay'),
('NLD', 'Pays-Bas'),
('PER', 'Pérou'),
('PHL', 'Philippines'),
('PCN', 'Îles Pitcairn'),
('POL', 'Pologne'),
('PYF', 'Polynésie française'),
('PRI', 'Porto Rico'),
('PRT', 'Portugal'),
('QAT', 'Qatar'),
('REU', 'La Réunion'),
('ROU', 'Roumanie'),
('GBR', 'Royaume-Uni'),
('RUS', 'Russie'),
('RWA', 'Rwanda'),
('ESH', 'République arabe sahraouie démocratique'),
('BLM', 'Saint-Barthélemy'),
('KNA', 'Saint-Christophe-et-Niévès'),
('SMR', 'Saint-Marin'),
('MAF', 'Saint-Martin'),
('SXM', 'Saint-Martin'),
('SPM', 'Saint-Pierre-et-Miquelon'),
('VAT', 'Saint-Siège (État de la Cité du Vatican)'),
('VCT', 'Saint-Vincent-et-les-Grenadines'),
('SHN', 'Sainte-Hélène, Ascension et Tristan da Cunha'),
('LCA', 'Sainte-Lucie'),
('SLB', 'Îles Salomon'),
('SLV', 'Salvador'),
('WSM', 'Samoa'),
('ASM', 'Samoa américaines'),
('STP', 'Sao Tomé-et-Principe'),
('SEN', 'Sénégal'),
('SRB', 'Serbie'),
('SYC', 'Seychelles'),
('SLE', 'Sierra Leone'),
('SGP', 'Singapour'),
('SVK', 'Slovaquie'),
('SVN', 'Slovénie'),
('SOM', 'Somalie'),
('SDN', 'Soudan'),
('SSD', 'Soudan du Sud'),
('LKA', 'Sri Lanka'),
('SWE', 'Suède'),
('CHE', 'Suisse'),
('SUR', 'Suriname'),
('SJM', 'Svalbard et île Jan Mayen'),
('SWZ', 'Eswatini'),
('SYR', 'Syrie'),
('TJK', 'Tadjikistan'),
('TWN', 'Taïwan / (République de Chine (Taïwan))'),
('TZA', 'Tanzanie'),
('TCD', 'Tchad'),
('CZE', 'Tchéquie'),
('ATF', 'Terres australes et antarctiques françaises'),
('THA', 'Thaïlande'),
('TLS', 'Timor oriental'),
('TGO', 'Togo'),
('TKL', 'Tokelau'),
('TON', 'Tonga'),
('TTO', 'Trinité-et-Tobago'),
('TUN', 'Tunisie'),
('TKM', 'Turkménistan'),
('TCA', 'Îles Turques-et-Caïques'),
('TUR', 'Turquie'),
('TUV', 'Tuvalu'),
('UKR', 'Ukraine'),
('URY', 'Uruguay'),
('VUT', 'Vanuatu'),
('VEN', 'Venezuela'),
('VGB', 'Îles Vierges britanniques'),
('VIR', 'Îles Vierges des États-Unis'),
('VNM', 'Viêt Nam'),
('WLF', 'Wallis-et-Futuna'),
('YEM', 'Yémen'),
('ZMB', 'Zambie'),
('ZWE', 'Zimbabwe');

INSERT IGNORE INTO Discipline (name_fr_disc, name_an_disc, category_disc) VALUES
('tir à l''arc', 'archery', 'OLYMPIC'),
('athlétisme', 'athletics', 'OLYMPIC'),
('badminton', 'badminton', 'OLYMPIC'),
('basketball', 'basketball', 'OLYMPIC'),
('basketball 3×3', 'basketball 3×3', 'OLYMPIC'),
('boxe', 'boxing', 'OLYMPIC'),
('canoë-kayak slalom', 'canoe slalom', 'OLYMPIC'),
('canoë sprint', 'canoe sprint', 'OLYMPIC'),
('cyclisme sur route', 'road cycling', 'OLYMPIC'),
('cyclisme sur piste', 'cycling track', 'OLYMPIC'),
('mountain bike (vtt)', 'mountain bike', 'OLYMPIC'),
('bmx freestyle', 'bmx freestyle', 'OLYMPIC'),
('bmx racing', 'bmx racing', 'OLYMPIC'),
('sports équestres', 'equestrian', 'OLYMPIC'),
('escrime', 'fencing', 'OLYMPIC'),
('football', 'football', 'OLYMPIC'),
('golf', 'golf', 'OLYMPIC'),
('gymnastique artistique', 'artistic gymnastics', 'OLYMPIC'),
('gymnastique rythmique', 'rhythmic gymnastics', 'OLYMPIC'),
('trampoline', 'trampoline', 'OLYMPIC'),
('handball', 'handball', 'OLYMPIC'),
('hockey', 'hockey', 'OLYMPIC'),
('judo', 'judo', 'OLYMPIC'),
('pentathlon moderne', 'modern pentathlon', 'OLYMPIC'),
('aviron', 'rowing', 'OLYMPIC'),
('rugby', 'rugby', 'OLYMPIC'),
('voile', 'sailing', 'OLYMPIC'),
('tir', 'shooting', 'OLYMPIC'),
('tennis de table', 'table tennis', 'OLYMPIC'),
('taekwondo', 'taekwondo', 'OLYMPIC'),
('taekwondo', 'tennis', 'OLYMPIC'),
('triathlon', 'triathlon', 'OLYMPIC'),
('volleyball', 'volleyball', 'OLYMPIC'),
('volleyball de plage', 'beach volleyball', 'OLYMPIC'),
('plongeon', 'diving', 'OLYMPIC'),
('natation marathon', 'marathon swimming', 'OLYMPIC'),
('natation artistique', 'artistic swimming', 'OLYMPIC'),
('natation', 'swimming', 'OLYMPIC'),
('waterpolo', 'water polo', 'OLYMPIC'),
('haltérophilie', 'weightlifting', 'OLYMPIC'),
('lutte', 'wrestling', 'OLYMPIC'),
('breaking', 'breaking', 'OLYMPIC'),
('escalade sportive', 'sport climbing', 'OLYMPIC'),
('skateboard', 'skateboarding', 'OLYMPIC'),
('surf', 'surfing', 'OLYMPIC'),
('cécifoot', 'blind football', 'PARALYMPIC'),
('boccia', 'boccia', 'PARALYMPIC'),
('goalball', 'goalball', 'PARALYMPIC'),
('para tir à l''arc', 'para archery', 'PARALYMPIC'),
('para athlétisme', 'para athletics', 'PARALYMPIC'),
('para badminton', 'para badminton', 'PARALYMPIC'),
('para canoë', 'para canoe', 'PARALYMPIC'),
('para cyclisme sur route', 'para cycling road', 'PARALYMPIC'),
('para cyclisme sur piste', 'para cycling track', 'PARALYMPIC'),
('para équitation (dressage)', 'para equestrian (para dressage)', 'PARALYMPIC'),
('para judo', 'para judo', 'PARALYMPIC'),
('para powerlifting', 'para powerlifting', 'PARALYMPIC'),
('para aviron', 'para rowing', 'PARALYMPIC'),
('para natation', 'para swimming', 'PARALYMPIC'),
('para tennis de table', 'para table tennis', 'PARALYMPIC'),
('para taekwondo', 'para taekwondo', 'PARALYMPIC'),
('para triathlon', 'para triathlon', 'PARALYMPIC'),
('para tir sportif', 'shooting para sport', 'PARALYMPIC'),
('volleyball assis', 'sitting volleyball', 'PARALYMPIC'),
('basket fauteuil', 'wheelchair basketball', 'PARALYMPIC'),
('escrime fauteuil', 'wheelchair fencing', 'PARALYMPIC'),
('rugby fauteuil', 'wheelchair rugby', 'PARALYMPIC'),
('tennis fauteuil', 'wheelchair tennis', 'PARALYMPIC');

INSERT IGNORE INTO Record (stat_record, date_record, id_event, id_athlete) VALUES
('9 s 63', '2012-08-05', NULL, 1),
('19 s 30', '2008-08-20', NULL, 1),
('43 s 03', '2016-08-15', NULL, NULL),
('1 min 40 s 91', '2012-08-09', NULL, 5),
('3 min 28 s 32', '2021-08-07', NULL, 6),
('12 min 57 s 82', '2008-08-23', NULL, 7),
('27 min 1 s 17', '2008-08-17', NULL, 7),
('2 h 6 min 32 s', '2008-08-24', NULL, 8),
('12 s 91', '2004-08-27', NULL, 9),
('45 s 94', '2021-08-03', NULL, 10),
('8 min 3 s 28', '2016-08-17', NULL, 11),
('1 h 18 min 46 s', '2012-08-04', NULL, 12),
('3 h 36 min 53 s', '2012-08-11', NULL, 13),
('8,90 m', '1968-10-18', NULL, 3),
('18,09 m', '1996-07-27', NULL, 14),
('2,39 m', '1996-07-28', NULL, 60),
('6,03 m', '2016-08-16', NULL, NULL),
('23,30 m', '2021-08-05', NULL, 16),
('69,89 m', '2004-08-23', NULL, 17),
('84,80 m', '1988-09-26', NULL, 18),
('90,57 m', '2008-08-23', NULL, 19),
('9018 points', '2021-08-05', NULL, 20),
('10 s 61', '2021-07-31', NULL, 2),
('21 s 34', '1988-09-29', NULL, 21),
('48 s 25', '1996-07-29', NULL, 22),
('1 min 53 s 43', '1980-07-27', NULL, 23),
('3 min 53 s 11', '2021-08-06', NULL, 24),
('14 min 26 s 17', '2016-08-19', NULL, 25),
('29 min 17 s 45', '2016-08-12', NULL, 26),
('2 h 23 min 07', '2012-08-05', NULL, 27),
('12 s 26', '2021-08-00', NULL, 28),
('51 s 46', '2021-08-04', NULL, 29),
('8 min 58 s 81', '2008-08-16', NULL, 30),
('1 h 25 min 16 s', '2012-08-11', NULL, 31),
('7,40 m', '1988-09-29', NULL, 32),
('15,67 m', '2021-08-00', NULL, 33),
('2,06 m', '2004-08-28', NULL, 34),
('5,05 m', '2008-08-18', NULL, 35),
('22,41 m', '1980-07-24', NULL, 36),
('72,30 m', '1988-09-29', NULL, 37),
('82,29 m', '2016-08-15', NULL, 38),
('71,53 m', '2004-08-27', NULL, NULL),
('7291 points', '1988-09-24', NULL, 32),
('21 s 07', '2021-08-00', NULL, 40),
('47 s 02', '2021-07-29', NULL, 40),
('1 min 42 s 96', '2008-08-12', NULL, 41),
('3 min 40 s 14', '2012-07-28', NULL, 43),
('7 min 41 s 28', '2021-07-27', NULL, 44),
('14 min 31 s 02', '2012-08-04', NULL, 43),
('51 s 85', '2016-08-13', NULL, 45),
('1 min 53 s 28', '2021-07-30', NULL, 46),
('57 s 13', '2016-08-07', NULL, 47),
('2 min 06 s 38', '2021-07-29', NULL, NULL),
('49 s 45', '2021-07-31', NULL, 40),
('1 min 51 s 25', '2021-07-28', NULL, 50),
('1 min 54 s 23', '2008-08-15', NULL, 41),
('4 min 03 s 84', '2008-08-10', NULL, 41),
('23 s 81', '2021-08-00', NULL, 51),
('51 s 96', '2021-07-30', NULL, 51),
('1 min 53 s 50', '2021-07-28', NULL, 52),
('3 min 56 s 46', '2016-08-07', NULL, 53),
('8 min 4 s 79', '2016-08-12', NULL, 53),
('15 min 35 s 35', '2021-07-26', NULL, 53),
('57 s 47', '2021-07-27', NULL, 54),
('2 min 4 s 06', '2012-08-03', NULL, 55),
('1 min 4 s 93', '2016-08-08', NULL, 56),
('2 min 18 s 95', '2021-07-30', NULL, 57),
('55 s 48', '2016-08-07', NULL, 58),
('2 min 3 s 86', '2021-07-29', NULL, 59),
('2 min 6 s 58', '2016-08-09', NULL, 61),
('4 min 26 s 36', '2016-08-06', NULL, 61);

INSERT IGNORE INTO Date_calendar (date_cal, medal_ceremony_date_cal) VALUES
('2024-07-26', False),
('2024-07-27', True),
('2024-07-28', True),
('2024-07-29', True),
('2024-07-30', True),
('2024-07-31', True),
('2024-08-01', True),
('2024-08-02', True),
('2024-08-03', True),
('2024-08-04', True),
('2024-08-05', True),
('2024-08-06', True),
('2024-08-07', True),
('2024-08-08', True),
('2024-08-09', True),
('2024-08-10', True),
('2024-08-11', True);

INSERT IGNORE INTO To_Serve (id_site, id_trans, num_ligne, station_name) VALUES
 (NULL, 1, 'RER A', 'Gare de Lyon'),
 (NULL, 1, 'RER D', 'Gare de Lyon'),
 (NULL, 1, 'Train R', 'Gare de Lyon'),
 (NULL, 4, 'Métro 1', 'Gare de Lyon'),
 (5, 4, 'Métro 10', 'Ségur'),
 (10, 1, 'RER B', 'Parc des expositions'),
 (10, 2, 'Tramway T3a', 'Georges Brassens'),
 (8, 1, 'RER E', 'Rosa Parks'),
 (4, 4, 'Métro 14', 'Pleyel'),
 (NULL, 1, 'Train L depuis la gare Saint-Lazare à Paris', 'Versailles Rive Droite'),
 (20, 1, 'RER C', 'Saint-Quentin-en-Yvelines'),
 (20, 1, 'Train N depuis la gare Montparnasse à Paris', 'Saint-Quentin-en-Yvelines'),
 (20, 1, 'Train U depuis la gare de La Défense', 'Saint-Quentin-en-Yvelines'),
 (7, 1, 'RER C', 'Invalides'),
 (7, 4, 'Métro 8', 'Invalides'),
 (7, 4, 'Métro 13', 'Invalides'),
 (NULL, 4, 'Métro 12', 'Assemblée Nationale'),
 (33, 4, 'Franklin D. Roosevelt »', 'Franklin D. Roosevelt'),
 (21, 1, 'RER C', 'Saint-Quentin-en-Yvelines'),
 (21, 1, 'Train N depuis la gare Montparnasse à Paris', 'Saint-Quentin-en-Yvelines'),
 (21, 1, 'Train U depuis la gare de La Défense', 'Saint-Quentin-en-Yvelines'),
 (NULL, 4, 'Ligne 83', 'Plage Roucas Blanc'),
 (11, 4, 'Métro 9', 'Marcel Sembat'),
 (11, 4, 'Métro 10', 'Porte d''Auteuil'),
 (11, 4, 'Métro 9', 'Porte de Saint-Cloud'),
 (11, 1, 'RER C', 'Pont du Garigliano'),
 (11, 1, 'RER A', 'Charles-de-Gaulle - Etoile'),
 (11, 4, 'Métro 1', 'Charles-de-Gaulle - Etoile'),
 (11, 4, 'Métro 2', 'Charles-de-Gaulle - Etoile'),
 (11, 4, 'Métro 6', 'Charles-de-Gaulle - Etoile'),
 (8, 1, 'RER A', 'Nanterre Préfecture'),
 (6, 1, 'RER C', 'Invalides'),
 (6, 4, 'Métro 8', 'Invalides'),
 (6, 4, 'Métro 13', 'Invalides'),
 (31, 1, 'RER B', 'Le Bourget'),
 (31, 2, 'Tramway T11', 'Le Bourget'),
 (24, 4, 'Ligne B', 'La Cité du Vin'),
 (2, 1, 'Train H depuis la gare du Nord à Paris', 'Saint-Denis'),
 (NULL, 4, 'Ligne M2', 'Sainte-Marguerite Dromel'),
 (12, 4, 'Métro 10', 'Porte d''Auteuil'),
 (5, 4, 'Métro 9', 'Alma Marceau'),
 (NULL, 1, 'RER C', 'Pont de l''Alma');

INSERT IGNORE INTO Event (name_event, format_event, gender_event, id_disc, id_record) VALUES
('100m', 'INDIVIDUAL', 'WOMAN', 2, 1),
('100m', 'INDIVIDUAL', 'MAN', 2, 1),
('200m', 'INDIVIDUAL', 'WOMAN', 2, 2),
('200m', 'INDIVIDUAL', 'MAN', 2, 2),
('400m', 'INDIVIDUAL', 'WOMAN', 2, 3),
('400m', 'INDIVIDUAL', 'MAN', 2, 3),
('800m', 'INDIVIDUAL', 'WOMAN', 2, 4),
('800m', 'INDIVIDUAL', 'MAN', 2, 4),
('1500m', 'INDIVIDUAL', 'WOMAN', 2, 5),
('1500m', 'INDIVIDUAL', 'MAN', 2, 5),
('5000m', 'INDIVIDUAL', 'WOMAN', 2, 6),
('5000m', 'INDIVIDUAL', 'MAN', 2, 6),
('10000m', 'INDIVIDUAL', 'WOMAN', 2, 7),
('10000m', 'INDIVIDUAL', 'MAN', 2, 7),
('400m haies', 'INDIVIDUAL', 'WOMAN', 2, 3),
('400m haies', 'INDIVIDUAL', 'MAN', 2, 3),
('3000m steeple', 'INDIVIDUAL', 'WOMAN', 2, 11),
('3000m steeple', 'INDIVIDUAL', 'MAN', 2, 11),
('Relais 4x100m', 'COLLECTIVE', 'WOMAN', 2, 1),
('Relais 4x100m', 'COLLECTIVE', 'MAN', 2, 1),
('Relais 4x400m', 'COLLECTIVE', 'WOMAN', 2, 3),
('Relais 4x400m', 'COLLECTIVE', 'MAN', 2, 3),
('Relais 4x400m', 'COLLECTIVE', 'MIXED', 2, 3),
('Saut en hauteur', 'INDIVIDUAL', 'WOMAN', 2, 16),
('Saut en hauteur', 'INDIVIDUAL', 'MAN', 2, 16),
('Saut à la perche', 'INDIVIDUAL', 'WOMAN', 2, 17),
('Saut à la perche', 'INDIVIDUAL', 'MAN', 2, 17),
('Saut en longueur', 'INDIVIDUAL', 'WOMAN', 2, 14),
('Saut en longueur', 'INDIVIDUAL', 'MAN', 2, 14),
('Triple saut', 'INDIVIDUAL', 'WOMAN', 2, 15),
('Triple saut', 'INDIVIDUAL', 'MAN', 2, 15),
('Lancer de poids', 'INDIVIDUAL', 'WOMAN', 2, NULL),
('Lancer de poids', 'INDIVIDUAL', 'MAN', 2, NULL),
('Lancer de disque', 'INDIVIDUAL', 'WOMAN', 2, NULL),
('Lancer de disque', 'INDIVIDUAL', 'MAN', 2, NULL),
('Lancer de marteau', 'INDIVIDUAL', 'WOMAN', 2, NULL),
('Lancer de marteau', 'INDIVIDUAL', 'MAN', 2, NULL),
('Lancer de javelot', 'INDIVIDUAL', 'WOMAN', 2, NULL),
('Lancer de javelot', 'INDIVIDUAL', 'MAN', 2, NULL),
('Décathlon', 'INDIVIDUAL', 'MAN', 2, 22),
('Heptathlon', 'INDIVIDUAL', 'WOMAN', 2, 43),
('110m haies', 'INDIVIDUAL', 'MAN', 2, 9),
('100m haies', 'INDIVIDUAL', 'WOMAN', 2, 1),
('20km marche', 'INDIVIDUAL', 'WOMAN', 2, 12),
('20km marche', 'INDIVIDUAL', 'MAN', 2, 12),
('Marche sur un marathon en relais', 'COLLECTIVE', 'MIXED', 2, NULL),
('Marathon', 'INDIVIDUAL', 'WOMAN', 2, 8),
('Marathon', 'INDIVIDUAL', 'MAN', 2, 8),
('Skiff', 'INDIVIDUAL', 'WOMAN', 25, NULL),
('Skiff', 'INDIVIDUAL', 'MAN', 25, NULL),
('Deux de pointe', 'COLLECTIVE', 'WOMAN', 25, NULL),
('Deux de pointe', 'COLLECTIVE', 'MAN', 25, NULL),
('Deux de couple', 'COLLECTIVE', 'WOMAN', 25, NULL),
('Deux de couple', 'COLLECTIVE', 'MAN', 25, NULL),
('Quatre de pointe sans barreur', 'COLLECTIVE', 'WOMAN', 25, NULL),
('Quatre de pointe sans barreur', 'COLLECTIVE', 'MAN', 25, NULL),
('Quatre de couple', 'COLLECTIVE', 'WOMAN', 25, NULL),
('Quatre de couple', 'COLLECTIVE', 'MAN', 25, NULL),
('Huit de pointe', 'INDIVIDUAL', 'WOMAN', 25, NULL),
('Huit de pointe', 'INDIVIDUAL', 'MAN', 25, NULL),
('Deux de couple poids léger', 'COLLECTIVE', 'WOMAN', 25, NULL),
('Deux de couple poids léger', 'COLLECTIVE', 'MAN', 25, NULL),
('Simple', 'INDIVIDUAL', 'WOMAN', 3, NULL),
('Simple', 'INDIVIDUAL', 'MAN', 3, NULL),
('Double', 'COLLECTIVE', 'WOMAN', 3, NULL),
('Double', 'COLLECTIVE', 'MAN', 3, NULL),
('Double', 'COLLECTIVE', 'MIXED', 3, NULL),
('Tournoi à 12 équipes', 'COLLECTIVE', 'WOMAN', 4, NULL),
('Tournoi à 12 équipes', 'COLLECTIVE', 'MAN', 4, NULL),
('Tournoi à 8 équipes', 'COLLECTIVE', 'WOMAN', 5, NULL),
('Tournoi à 8 équipes', 'COLLECTIVE', 'MAN', 5, NULL),
('C-1 1000m', 'INDIVIDUAL', 'MAN', 8, NULL),
('C-1 200m', 'INDIVIDUAL', 'WOMAN', 8, NULL),
('C-2 500m', 'INDIVIDUAL', 'WOMAN', 8, NULL),
('C-2 500m', 'INDIVIDUAL', 'MAN', 8, NULL),
('K-1 1000m', 'INDIVIDUAL', 'MAN', 8, NULL),
('K-1 500m', 'INDIVIDUAL', 'WOMAN', 8, NULL),
('K-2 500m', 'INDIVIDUAL', 'WOMAN', 8, NULL),
('K-2 500m', 'INDIVIDUAL', 'MAN', 8, NULL),
('K-4 500m', 'INDIVIDUAL', 'WOMAN', 8, NULL),
('K-4 500m', 'INDIVIDUAL', 'MAN', 8, NULL),
('K-1', 'INDIVIDUAL', 'WOMAN', 7, NULL),
('K-1', 'INDIVIDUAL', 'MAN', 7, NULL),
('C-1', 'INDIVIDUAL', 'WOMAN', 7, NULL),
('C-1', 'INDIVIDUAL', 'MAN', 7, NULL),
('Kayak cross', 'INDIVIDUAL', 'WOMAN', 7, NULL),
('Kayak cross', 'INDIVIDUAL', 'MAN', 7, NULL),
('Vitesse individuelle', 'INDIVIDUAL', 'WOMAN', 10, NULL),
('Vitesse individuelle', 'INDIVIDUAL', 'MAN', 10, NULL),
('Vitesse par équipe', 'COLLECTIVE', 'WOMAN', 10, NULL),
('Vitesse par équipe', 'COLLECTIVE', 'MAN', 10, NULL),
('Keirin', 'INDIVIDUAL', 'WOMAN', 10, NULL),
('Keirin', 'INDIVIDUAL', 'MAN', 10, NULL),
('Poursuite par équipe', 'COLLECTIVE', 'WOMAN', 10, NULL),
('Poursuite par équipe', 'COLLECTIVE', 'MAN', 10, NULL),
('Omnium', 'INDIVIDUAL', 'WOMAN', 10, NULL),
('Omnium', 'INDIVIDUAL', 'MAN', 10, NULL),
('Madison', 'INDIVIDUAL', 'WOMAN', 10, NULL),
('Madison', 'INDIVIDUAL', 'MAN', 10, NULL),
('Epreuves contre la montre', 'INDIVIDUAL', 'WOMAN', 9, NULL),
('Epreuves contre la montre', 'INDIVIDUAL', 'MAN', 9, NULL),
('Epreuves en ligne', 'INDIVIDUAL', 'WOMAN', 9, NULL),
('Epreuves en ligne', 'INDIVIDUAL', 'MAN', 9, NULL),
('BMX freestyle', 'INDIVIDUAL', 'WOMAN', 12, NULL),
('BMX freestyle', 'INDIVIDUAL', 'MAN', 12, NULL),
('BMX racing', 'INDIVIDUAL', 'WOMAN', 13, NULL),
('BMX racing', 'INDIVIDUAL', 'MAN', 13, NULL),
('Cross-country', 'INDIVIDUAL', 'WOMAN', NULL, NULL),
('Cross-country', 'INDIVIDUAL', 'MAN', NULL, NULL),
('Epée individuelle', 'INDIVIDUAL', 'WOMAN', 15, NULL),
('Epée individuelle', 'INDIVIDUAL', 'MAN', 15, NULL),
('Fleuret individuel', 'INDIVIDUAL', 'WOMAN', 15, NULL),
('Fleuret individuel', 'INDIVIDUAL', 'MAN', 15, NULL),
('Sabre individuel', 'INDIVIDUAL', 'WOMAN', 15, NULL),
('Sabre individuel', 'INDIVIDUAL', 'MAN', 15, NULL),
('Epée par équipes', 'COLLECTIVE', 'WOMAN', 15, NULL),
('Epée par équipes', 'COLLECTIVE', 'MAN', 15, NULL),
('Fleuret par équipes', 'COLLECTIVE', 'WOMAN', 15, NULL),
('Fleuret par équipes', 'COLLECTIVE', 'MAN', 15, NULL),
('Sabre par équipes', 'COLLECTIVE', 'WOMAN', 15, NULL),
('Sabre par équipes', 'COLLECTIVE', 'MAN', 15, NULL),
('Tournoi de football', 'COLLECTIVE', 'WOMAN', 16, NULL),
('Tournoi de football', 'COLLECTIVE', 'MAN', 16, NULL),
('Tournoi de golf individuel', 'INDIVIDUAL', 'WOMAN', 17, NULL),
('Tournoi de golf individuel', 'INDIVIDUAL', 'MAN', 17, NULL),
('Concours par équipes', 'COLLECTIVE', 'WOMAN', 18, NULL),
('Concours par équipes', 'COLLECTIVE', 'MAN', 18, NULL),
('Concours général', 'INDIVIDUAL', 'WOMAN', 18, NULL),
('Concours général', 'INDIVIDUAL', 'MAN', 18, NULL),
('Exercices au sol', 'INDIVIDUAL', 'WOMAN', 18, NULL),
('Exercices au sol', 'INDIVIDUAL', 'MAN', 18, NULL),
('Saut', 'INDIVIDUAL', 'WOMAN', 18, NULL),
('Saut', 'INDIVIDUAL', 'MAN', 18, NULL),
('Barres asymétriques', 'INDIVIDUAL', 'WOMAN', 18, NULL),
('Poutre', 'INDIVIDUAL', 'WOMAN', 18, NULL),
('Cheval d''arçons', 'INDIVIDUAL', 'MAN', 18, NULL),
('Anneaux', 'INDIVIDUAL', 'MAN', 18, NULL),
('Barres parallèles', 'INDIVIDUAL', 'MAN', 18, NULL),
('Barre fixe', 'INDIVIDUAL', 'MAN', 18, NULL),
('Concours des ensembles', 'COLLECTIVE', 'WOMAN', 19, NULL),
('Concours individuel', 'INDIVIDUAL', 'WOMAN', 19, NULL),
('Individuel', 'INDIVIDUAL', 'WOMAN', 20, NULL),
('Individuel', 'INDIVIDUAL', 'MAN', 20, NULL),
('49kg', 'INDIVIDUAL', 'WOMAN', 40, NULL),
('59kg', 'INDIVIDUAL', 'WOMAN', 40, NULL),
('71kg', 'INDIVIDUAL', 'WOMAN', 40, NULL),
('81kg', 'INDIVIDUAL', 'WOMAN', 40, NULL),
('+81kg', 'INDIVIDUAL', 'WOMAN', 40, NULL),
('61kg', 'INDIVIDUAL', 'MAN', 40, NULL),
('73kg', 'INDIVIDUAL', 'MAN', 40, NULL),
('89kg', 'INDIVIDUAL', 'MAN', 40, NULL),
('102kg', 'INDIVIDUAL', 'MAN', 40, NULL),
('+102kg', 'INDIVIDUAL', 'MAN', 40, NULL),
('Tournoi de handball', 'COLLECTIVE', 'WOMAN', 21, NULL),
('Tournoi de handball', 'COLLECTIVE', 'MAN', 21, NULL),
('Tournoi de hockey', 'COLLECTIVE', 'WOMAN', 22, NULL),
('Tournoi de hockey', 'COLLECTIVE', 'MAN', 22, NULL),
('Tournois -48kg individuel', 'INDIVIDUAL', 'WOMAN', 23, NULL),
('Tournois -52kg individuel', 'INDIVIDUAL', 'WOMAN', 23, NULL),
('Tournois -57kg individuel', 'INDIVIDUAL', 'WOMAN', 23, NULL),
('Tournois -63kg individuel', 'INDIVIDUAL', 'WOMAN', 23, NULL),
('Tournois -70kg individuel', 'INDIVIDUAL', 'WOMAN', 23, NULL),
('Tournois -78kg individuel', 'INDIVIDUAL', 'WOMAN', 23, NULL),
('Tournois +78kg individuel', 'INDIVIDUAL', 'WOMAN', 23, NULL),
('Tournois -60kg individuel', 'INDIVIDUAL', 'MAN', 23, NULL),
('Tournois -66kg individuel', 'INDIVIDUAL', 'MAN', 23, NULL),
('Tournois -73kg individuel', 'INDIVIDUAL', 'MAN', 23, NULL),
('Tournois -81kg individuel', 'INDIVIDUAL', 'MAN', 23, NULL),
('Tournois -90kg individuel', 'INDIVIDUAL', 'MAN', 23, NULL),
('Tournois -100kg individuel', 'INDIVIDUAL', 'MAN', 23, NULL),
('Tournois +100kg individuel', 'INDIVIDUAL', 'MAN', 23, NULL),
('Tournois par équipes', 'COLLECTIVE', 'MIXED', 23, NULL),
('Lutte libre -50kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Lutte libre -53kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Lutte libre -57kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Lutte libre -62kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Lutte libre -68kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Lutte libre -76kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Lutte libre -57kg', 'INDIVIDUAL', 'MAN', 41, NULL),
('Lutte libre -65kg', 'INDIVIDUAL', 'MAN', 41, NULL),
('Lutte libre -74kg', 'INDIVIDUAL', 'MAN', 41, NULL),
('Lutte libre -86kg', 'INDIVIDUAL', 'MAN', 41, NULL),
('Lutte libre -97kg', 'INDIVIDUAL', 'MAN', 41, NULL),
('Lutte libre -125kg', 'INDIVIDUAL', 'MAN', 41, NULL),
('Lutte gréco-romaine -60kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Lutte gréco-romaine -67kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Lutte gréco-romaine -77kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Lutte gréco-romaine -87kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Lutte gréco-romaine -97kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Lutte gréco-romaine -130kg', 'INDIVIDUAL', 'WOMAN', 41, NULL),
('Compétition individuelle', 'INDIVIDUAL', 'WOMAN', 24, NULL),
('Compétition individuelle', 'INDIVIDUAL', 'MAN', 24, NULL),
('Tournoi de rugby à 7', 'COLLECTIVE', 'WOMAN', 26, NULL),
('Tournoi de rugby à 7', 'COLLECTIVE', 'MAN', 26, NULL),
('50m nage libre', 'INDIVIDUAL', 'WOMAN', 38, 44),
('50m nage libre', 'INDIVIDUAL', 'MAN', 38, 44),
('100m nage libre', 'INDIVIDUAL', 'WOMAN', 38, 45),
('100m nage libre', 'INDIVIDUAL', 'MAN', 38, 45),
('200m nage libre', 'INDIVIDUAL', 'WOMAN', 38, 46),
('200m nage libre', 'INDIVIDUAL', 'MAN', 38, 46),
('400m nage libre', 'INDIVIDUAL', 'WOMAN', 38, 47),
('400m nage libre', 'INDIVIDUAL', 'MAN', 38, 47),
('800m nage libre', 'INDIVIDUAL', 'WOMAN', 38, 48),
('800m nage libre', 'INDIVIDUAL', 'MAN', 38, 48),
('1500mnage libre', 'INDIVIDUAL', 'WOMAN', 38, NULL),
('1500mnage libre', 'INDIVIDUAL', 'MAN', 38, NULL),
('100m dos', 'INDIVIDUAL', 'WOMAN', 38, 50),
('100m dos', 'INDIVIDUAL', 'MAN', 38, 50),
('200m dos', 'INDIVIDUAL', 'WOMAN', 38, 51),
('200m dos', 'INDIVIDUAL', 'MAN', 38, 51),
('100mbrass', 'INDIVIDUAL', 'WOMAN', 38, NULL),
('100mbrass', 'INDIVIDUAL', 'MAN', 38, NULL),
('200m brasse', 'INDIVIDUAL', 'WOMAN', 38, 53),
('200m brasse', 'INDIVIDUAL', 'MAN', 38, 53),
('100m papillon', 'INDIVIDUAL', 'WOMAN', 38, 54),
('100m papillon', 'INDIVIDUAL', 'MAN', 38, 54),
('200m papillon', 'INDIVIDUAL', 'WOMAN', 38, 55),
('200m papillon', 'INDIVIDUAL', 'MAN', 38, 55),
('200m quatre nages individuel', 'INDIVIDUAL', 'WOMAN', 38, NULL),
('200m quatre nages individuel', 'INDIVIDUAL', 'MAN', 38, NULL),
('400m quatre nages individuel', 'INDIVIDUAL', 'WOMAN', 38, NULL),
('400m quatre nages individuel', 'INDIVIDUAL', 'MAN', 38, NULL),
('Relais4x100m nage libre', 'COLLECTIVE', 'WOMAN', 38, 45),
('Relais4x100m nage libre', 'COLLECTIVE', 'MAN', 38, 45),
('Relais 4x200m nage libre', 'COLLECTIVE', 'WOMAN', 38, 46),
('Relais 4x200m nage libre', 'COLLECTIVE', 'MAN', 38, 46),
('Relais4x100m quatre nages', 'COLLECTIVE', 'WOMAN', 38, NULL),
('Relais4x100m quatre nages', 'COLLECTIVE', 'MAN', 38, NULL),
('Relais 4x100m quatre nages', 'COLLECTIVE', 'MIXED', 38, NULL),
('Duo libre', 'COLLECTIVE', 'MIXED', 37, NULL),
('Duo technique', 'COLLECTIVE', 'MIXED', 37, NULL),
('Finale des duos', 'COLLECTIVE', 'MIXED', 37, NULL),
('Equipes libres', 'COLLECTIVE', 'MIXED', 37, NULL),
('Equipes techniques', 'COLLECTIVE', 'MIXED', 37, NULL),
('Natation marathon, 10km', 'INDIVIDUAL', 'WOMAN', 36, NULL),
('Natation marathon, 10km', 'INDIVIDUAL', 'MAN', 36, NULL),
('Haut-vol 10m', 'INDIVIDUAL', 'MIXED', 35, NULL),
('Haut-vol 10m', 'INDIVIDUAL', 'MIXED', 35, NULL),
('Haut-vol 10m synchronisé', 'COLLECTIVE', 'MIXED', 35, NULL),
('Haut-vol 10m synchronisé', 'COLLECTIVE', 'MIXED', 35, NULL),
('Tremplin 3m', 'INDIVIDUAL', 'MIXED', 35, NULL),
('Tremplin 3m', 'INDIVIDUAL', 'MIXED', 35, NULL),
('Tremplin 3m synchronisé', 'COLLECTIVE', 'MIXED', 35, NULL),
('Tremplin 3m synchronisé', 'COLLECTIVE', 'MIXED', 35, NULL),
('Tournoi de water-polo', 'COLLECTIVE', 'WOMAN', NULL, NULL),
('Tournoi de water-polo', 'COLLECTIVE', 'MAN', NULL, NULL),
('Concours complet individuel', 'INDIVIDUAL', 'MIXED', 14, NULL),
('Concours complet par équipes', 'COLLECTIVE', 'MIXED', 14, NULL),
('Dressage individuel', 'INDIVIDUAL', 'MIXED', 14, NULL),
('Dressage par équipes', 'COLLECTIVE', 'MIXED', 14, NULL),
('Saut d''obstacle individuel', 'INDIVIDUAL', 'MIXED', 14, NULL),
('Saut d''obstacle par équipes', 'COLLECTIVE', 'MIXED', 14, NULL),
('-58kg', 'INDIVIDUAL', 'MAN', 30, NULL),
('-68kg', 'INDIVIDUAL', 'MAN', 30, NULL),
('-80kg', 'INDIVIDUAL', 'MAN', 30, NULL),
('+80kg', 'INDIVIDUAL', 'MAN', 30, NULL),
('-49kg', 'INDIVIDUAL', 'WOMAN', 30, NULL),
('-57kg', 'INDIVIDUAL', 'WOMAN', 30, NULL),
('-67kg', 'INDIVIDUAL', 'WOMAN', 30, NULL),
('+67kg', 'INDIVIDUAL', 'WOMAN', 30, NULL),
('Simple', 'INDIVIDUAL', 'WOMAN', NULL, NULL),
('Simple', 'INDIVIDUAL', 'MAN', NULL, NULL),
('Double', 'COLLECTIVE', 'WOMAN', NULL, NULL),
('Double', 'COLLECTIVE', 'MAN', NULL, NULL),
('Double', 'COLLECTIVE', 'MIXED', NULL, NULL),
('Simple', 'INDIVIDUAL', 'WOMAN', 29, NULL),
('Simple', 'INDIVIDUAL', 'MAN', 29, NULL),
('Par équipes', 'COLLECTIVE', 'WOMAN', 29, NULL),
('Par équipes', 'COLLECTIVE', 'MAN', 29, NULL),
('Double', 'COLLECTIVE', 'MIXED', 29, NULL),
('Pistolet à air comprimé 10m', 'INDIVIDUAL', 'WOMAN', 28, NULL),
('Pistolet à air comprimé 10m', 'INDIVIDUAL', 'MAN', 28, NULL),
('Pistolet à air comprimé 10m', 'COLLECTIVE', 'MIXED', 28, NULL),
('Carabine à air comprimé 10m', 'INDIVIDUAL', 'WOMAN', 28, NULL),
('Carabine à air comprimé 10m', 'INDIVIDUAL', 'MAN', 28, NULL),
('Carabine à air comprimé 10m', 'COLLECTIVE', 'MIXED', 28, NULL),
('Carabine 50m 3 positions', 'INDIVIDUAL', 'WOMAN', 28, NULL),
('Carabine 50m 3 positions', 'INDIVIDUAL', 'MAN', 28, NULL),
('Skeet olympique', 'INDIVIDUAL', 'WOMAN', 28, NULL),
('Skeet olympique', 'INDIVIDUAL', 'MAN', 28, NULL),
('Skeet olympique', 'COLLECTIVE', 'MIXED', 28, NULL),
('Fosse olympique', 'INDIVIDUAL', 'WOMAN', 28, NULL),
('Fosse olympique', 'INDIVIDUAL', 'MAN', 28, NULL),
('Pistolet rapide 25m', 'INDIVIDUAL', 'WOMAN', 28, NULL),
('Pistolet rapide 25m', 'INDIVIDUAL', 'MAN', 28, NULL),
('Individuel', 'INDIVIDUAL', 'WOMAN', NULL, NULL),
('Individuel', 'INDIVIDUAL', 'MAN', NULL, NULL),
('Par équipes', 'COLLECTIVE', 'WOMAN', NULL, NULL),
('Par équipes', 'COLLECTIVE', 'MAN', NULL, NULL),
('Par équipes', 'COLLECTIVE', 'MIXED', NULL, NULL),
('Epreuve individuelle', 'INDIVIDUAL', 'WOMAN', 32, NULL),
('Epreuve individuelle', 'INDIVIDUAL', 'MAN', 32, NULL),
('Epreuve de relais', 'COLLECTIVE', 'MIXED', 32, NULL),
('dériveur solitaire ILCA 6, skiff 49er FX, Planche à voile IQ foil, formula kite.', 'INDIVIDUAL', 'WOMAN', 27, NULL),
('dériveur solitaire ILCA 7, skiff 49er, Planche à voile IQ foil, formula kite.', 'INDIVIDUAL', 'MAN', 27, NULL),
('multicoque mixte Nacra 17 à foils, dériveur double mixte - 470.', 'COLLECTIVE', 'MIXED', 27, NULL),
('Tournoi de volleyball', 'COLLECTIVE', 'WOMAN', 33, NULL),
('Tournoi de volleyball', 'COLLECTIVE', 'MAN', 33, NULL),
('Tournoi de volleyball de plage', 'COLLECTIVE', 'WOMAN', 34, NULL),
('Tournoi de volleyball de plage', 'COLLECTIVE', 'MAN', 34, NULL),
('Battle B-girls', 'INDIVIDUAL', 'WOMAN', 42, NULL),
('Battle B-boys', 'INDIVIDUAL', 'MAN', 42, NULL),
('Combiné bloc-difficulté', 'INDIVIDUAL', 'WOMAN', 43, NULL),
('Combiné bloc-difficulté', 'INDIVIDUAL', 'MAN', 43, NULL),
('Vitesse', 'INDIVIDUAL', 'WOMAN', 43, NULL),
('Vitesse', 'INDIVIDUAL', 'MAN', 43, NULL),
('Skateboard park', 'INDIVIDUAL', 'WOMAN', 44, NULL),
('Skateboard park', 'INDIVIDUAL', 'MAN', 44, NULL),
('Skateboard street', 'INDIVIDUAL', 'WOMAN', 44, NULL),
('Skateboard street', 'INDIVIDUAL', 'MAN', 44, NULL),
('Shortboard', 'INDIVIDUAL', 'WOMAN', 45, NULL),
('Shortboard', 'INDIVIDUAL', 'MAN', 45, NULL),
('Individuel BC1', 'INDIVIDUAL', 'WOMAN', 47, NULL),
('Individuel BC1', 'INDIVIDUAL', 'MAN', 47, NULL),
('Individuel BC2', 'INDIVIDUAL', 'WOMAN', 47, NULL),
('Individuel BC2', 'INDIVIDUAL', 'MAN', 47, NULL),
('Individuel BC3', 'INDIVIDUAL', 'WOMAN', 47, NULL),
('Individuel BC3', 'INDIVIDUAL', 'MAN', 47, NULL),
('Individuel BC4', 'INDIVIDUAL', 'WOMAN', 47, NULL),
('Individuel BC4', 'INDIVIDUAL', 'MAN', 47, NULL),
('Equipe BC1-2', 'COLLECTIVE', 'MIXED', 47, NULL),
('Equipe BC3', 'COLLECTIVE', 'MIXED', 47, NULL),
('Equipe BC4', 'COLLECTIVE', 'MIXED', 47, NULL),
('Tournoi B1 de 8 équipes', 'COLLECTIVE', 'MAN', 46, NULL),
('Epée catégorie A', 'INDIVIDUAL', 'WOMAN', 66, NULL),
('Epée catégorie A', 'INDIVIDUAL', 'MAN', 66, NULL),
('Epée catégorie B', 'INDIVIDUAL', 'WOMAN', 66, NULL),
('Epée catégorie B', 'INDIVIDUAL', 'MAN', 66, NULL),
('Epée par équipe', 'COLLECTIVE', 'WOMAN', 66, NULL),
('Epée par équipe', 'COLLECTIVE', 'MAN', 66, NULL),
('Fleuret catégorie A', 'INDIVIDUAL', 'WOMAN', 66, NULL),
('Fleuret catégorie A', 'INDIVIDUAL', 'MAN', 66, NULL),
('Fleuret catégorie B', 'INDIVIDUAL', 'WOMAN', 66, NULL),
('Fleuret catégorie B', 'INDIVIDUAL', 'MAN', 66, NULL),
('Fleuret par équipe', 'COLLECTIVE', 'WOMAN', 66, NULL),
('Fleuret par équipe', 'COLLECTIVE', 'MAN', 66, NULL),
('Sabre catégorie A', 'INDIVIDUAL', 'WOMAN', 66, NULL),
('Sabre catégorie A', 'INDIVIDUAL', 'MAN', 66, NULL),
('Sabre catégorie B', 'INDIVIDUAL', 'WOMAN', 66, NULL),
('Sabre catégorie B', 'INDIVIDUAL', 'MAN', 66, NULL),
('Tournoi 8 équipes', 'COLLECTIVE', 'WOMAN', 48, NULL),
('Tournoi 8 équipes', 'COLLECTIVE', 'MAN', 48, NULL),
('100m T11, T12, T13, T34, T35, T36, T37, T38, T44, T47, T53, T54, T63, T64', 'INDIVIDUAL', 'WOMAN', 50, 1),
('100m T11, T12, T13, T34, T35, T36, T37, T38, T44, T47, T53, T54, T63, T64', 'INDIVIDUAL', 'MAN', 50, 1),
('100m T51, T52', 'INDIVIDUAL', 'MAN', 50, 1),
('200m T35, T37, T64', 'INDIVIDUAL', 'WOMAN', 50, 2),
('200m T35, T37, T64', 'INDIVIDUAL', 'MAN', 50, 2),
('200m T11, T12, T36, T47', 'INDIVIDUAL', 'WOMAN', 50, 2),
('200m T51', 'INDIVIDUAL', 'MAN', 50, 2),
('400m T11, T12, T13, T20, T37, T38, T47, T53, T54', 'INDIVIDUAL', 'WOMAN', 50, 3),
('400m T11, T12, T13, T20, T37, T38, T47, T53, T54', 'INDIVIDUAL', 'MAN', 50, 3),
('400m T36, T52, T62', 'INDIVIDUAL', 'MAN', 50, 3),
('800m T34, T53, T54', 'INDIVIDUAL', 'WOMAN', 50, 4),
('800m T34, T53, T54', 'INDIVIDUAL', 'MAN', 50, 4),
('1500m T11, T13, T20, T54', 'INDIVIDUAL', 'WOMAN', 50, 5),
('1500m T11, T13, T20, T54', 'INDIVIDUAL', 'MAN', 50, 5),
('1500m T38, T46', 'INDIVIDUAL', 'MAN', 50, 5),
('5000m T54', 'INDIVIDUAL', 'WOMAN', 50, 6),
('5000m T54', 'INDIVIDUAL', 'MAN', 50, 6),
('5000m T11, T13', 'INDIVIDUAL', 'MAN', 50, 6),
('Relais 4x100m', 'COLLECTIVE', 'MIXED', 50, 1),
('Marathon T12, T54', 'INDIVIDUAL', 'WOMAN', 50, 8),
('Marathon T12, T54', 'INDIVIDUAL', 'MAN', 50, 8),
('Saut en longueur T11, T12, T20, T37, T38, T47, T63, T64', 'INDIVIDUAL', 'WOMAN', 50, 14),
('Saut en longueur T11, T12, T20, T37, T38, T47, T63, T64', 'INDIVIDUAL', 'MAN', 50, 14),
('Saut en longueur T13, T36', 'INDIVIDUAL', 'MAN', 50, 14),
('Lancer de massue F32', 'INDIVIDUAL', 'WOMAN', 50, NULL),
('Lancer de massue F32', 'INDIVIDUAL', 'MAN', 50, NULL),
('Lancer de massue F51', 'INDIVIDUAL', 'MAN', 50, NULL),
('Saut en hauteur T47, T63, T64', 'INDIVIDUAL', 'MAN', 50, 16),
('Lancer de disque F11, F64', 'INDIVIDUAL', 'WOMAN', 50, NULL),
('Lancer de disque F11, F64', 'INDIVIDUAL', 'MAN', 50, NULL),
('Lancer de disque F38, F41, F53, F55, F57', 'INDIVIDUAL', 'WOMAN', 50, NULL),
('Lancer de disque F37, F52, F56', 'INDIVIDUAL', 'MAN', 50, NULL),
('Lancer de javelot F13, F34, F46, F54', 'INDIVIDUAL', 'WOMAN', 50, NULL),
('Lancer de javelot F13, F34, F46, F54', 'INDIVIDUAL', 'MAN', 50, NULL),
('Lancer de javelot F56', 'INDIVIDUAL', 'WOMAN', 50, NULL),
('Lancer de javelot F38, F41, F57, F64', 'INDIVIDUAL', 'MAN', 50, NULL),
('Lancer de poids F12, F20, F32, F33, F34, F35, F37, F40, FR41, F46, F57', 'INDIVIDUAL', 'WOMAN', 50, NULL),
('Lancer de poids F12, F20, F32, F33, F34, F35, F37, F40, FR41, F46, F57', 'INDIVIDUAL', 'MAN', 50, NULL),
('Lancer de poids F11, F36 , F53, F55, F63', 'INDIVIDUAL', 'MAN', 50, NULL),
('Skiff PR1, M1X, W1x', 'INDIVIDUAL', 'MIXED', 58, NULL),
('Deux de couple PR2 Mix2x', 'COLLECTIVE', 'MIXED', 58, NULL),
('Deux de couple PR3 Mix2x', 'COLLECTIVE', 'MIXED', 58, NULL),
('Quatre de pointe avec barreur PR3 Mix4+', 'COLLECTIVE', 'MIXED', 58, NULL),
('Simple WH1', 'INDIVIDUAL', 'WOMAN', 51, NULL),
('Simple WH1', 'INDIVIDUAL', 'MAN', 51, NULL),
('Simple WH2', 'INDIVIDUAL', 'WOMAN', 51, NULL),
('Simple WH2', 'INDIVIDUAL', 'MAN', 51, NULL),
('Simple SL3', 'INDIVIDUAL', 'WOMAN', 51, NULL),
('Simple SL3', 'INDIVIDUAL', 'MAN', 51, NULL),
('Simple SL4', 'INDIVIDUAL', 'WOMAN', 51, NULL),
('Simple SL4', 'INDIVIDUAL', 'MAN', 51, NULL),
('Simple SU5', 'INDIVIDUAL', 'WOMAN', 51, NULL),
('Simple SU5', 'INDIVIDUAL', 'MAN', 51, NULL),
('Simple SH6', 'INDIVIDUAL', 'WOMAN', 51, NULL),
('Simple SH6', 'INDIVIDUAL', 'MAN', 51, NULL),
('Double WH1-2', 'COLLECTIVE', 'WOMAN', 51, NULL),
('Double WH1-2', 'COLLECTIVE', 'MAN', 51, NULL),
('Double SL3-SU5', 'COLLECTIVE', 'MIXED', 51, NULL),
('Double SH6', 'COLLECTIVE', 'MIXED', 51, NULL),
('KL1', 'INDIVIDUAL', 'WOMAN', 52, NULL),
('KL1', 'INDIVIDUAL', 'MAN', 52, NULL),
('KL2', 'INDIVIDUAL', 'WOMAN', 52, NULL),
('KL2', 'INDIVIDUAL', 'MAN', 52, NULL),
('KL3', 'INDIVIDUAL', 'WOMAN', 52, NULL),
('KL3', 'INDIVIDUAL', 'MAN', 52, NULL),
('VL2', 'INDIVIDUAL', 'WOMAN', 52, NULL),
('VL2', 'INDIVIDUAL', 'MAN', 52, NULL),
('VL3', 'INDIVIDUAL', 'WOMAN', 52, NULL),
('VL3', 'INDIVIDUAL', 'MAN', 52, NULL),
('Course sur route C1-2-3', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Course sur route C1-2-3', 'INDIVIDUAL', 'MAN', 53, NULL),
('Course sur route C4-5', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Course sur route C4-5', 'INDIVIDUAL', 'MAN', 53, NULL),
('Course sur route H1-2', 'INDIVIDUAL', 'MAN', 53, NULL),
('Course sur route H1-2-3-4', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Course sur route H3', 'INDIVIDUAL', 'MAN', 53, NULL),
('Course sur route H4', 'INDIVIDUAL', 'MAN', 53, NULL),
('Course sur route H5', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Course sur route H5', 'INDIVIDUAL', 'MAN', 53, NULL),
('Course sur route T1-2', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Course sur route T1-2', 'INDIVIDUAL', 'MAN', 53, NULL),
('Course sur route B', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Course sur route B', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre C1-2-3', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Contre la montre C1', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre C2', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre C3', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre C4', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Contre la montre C4', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre C5', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Contre la montre C5', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre H1', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre H2', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre H3', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre H4', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre H5', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre H1-2-3', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Contre la montre H4-5', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Contre la montre T1-2', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Contre la montre T1-2', 'INDIVIDUAL', 'MAN', 53, NULL),
('Contre la montre B', 'INDIVIDUAL', 'WOMAN', 53, NULL),
('Contre la montre B', 'INDIVIDUAL', 'MAN', 53, NULL),
('Relais par équipe H1-5', 'COLLECTIVE', 'MIXED', 53, NULL),
('Kilomètre C1-2-3', 'INDIVIDUAL', 'MAN', 54, NULL),
('Kilomètre C4-5', 'INDIVIDUAL', 'MAN', 54, NULL),
('500m C1-2-3', 'INDIVIDUAL', 'WOMAN', 54, NULL),
('500m C4-5', 'INDIVIDUAL', 'WOMAN', 54, NULL),
('Poursuite C1-2-3', 'INDIVIDUAL', 'WOMAN', 54, NULL),
('Poursuite C1', 'INDIVIDUAL', 'MAN', 54, NULL),
('Poursuite C2', 'INDIVIDUAL', 'MAN', 54, NULL),
('Poursuite C3', 'INDIVIDUAL', 'MAN', 54, NULL),
('Poursuite C4', 'INDIVIDUAL', 'WOMAN', 54, NULL),
('Poursuite C4', 'INDIVIDUAL', 'MAN', 54, NULL),
('Poursuite C5', 'INDIVIDUAL', 'WOMAN', 54, NULL),
('Poursuite C5', 'INDIVIDUAL', 'MAN', 54, NULL),
('Kilomètre B', 'INDIVIDUAL', 'WOMAN', 54, NULL),
('Kilomètre B', 'INDIVIDUAL', 'MAN', 54, NULL),
('Poursuite B', 'INDIVIDUAL', 'WOMAN', 54, NULL),
('Poursuite B', 'INDIVIDUAL', 'MAN', 54, NULL),
('Sprint par équipe C1-5', 'COLLECTIVE', 'MIXED', 54, NULL),
('Grand Prix individuel grade I', 'INDIVIDUAL', 'MIXED', NULL, NULL),
('Grand Prix individuel grade II', 'INDIVIDUAL', 'MIXED', NULL, NULL),
('Grand Prix individuel grade III', 'INDIVIDUAL', 'MIXED', NULL, NULL),
('Grand Prix individuel grade IV', 'INDIVIDUAL', 'MIXED', NULL, NULL),
('Grand Prix individuel grade V', 'INDIVIDUAL', 'MIXED', NULL, NULL),
('Grand Prix par équipe - Open', 'COLLECTIVE', 'MIXED', NULL, NULL),
('Grand Prix libre individuel grade I', 'INDIVIDUAL', 'MIXED', NULL, NULL),
('Grand Prix libre individuel grade II', 'INDIVIDUAL', 'MIXED', NULL, NULL),
('Grand Prix libre individuel grade III', 'INDIVIDUAL', 'MIXED', NULL, NULL),
('Grand Prix libre individuel grade IV', 'INDIVIDUAL', 'MIXED', NULL, NULL),
('Grand Prix libre individuel grade V', 'INDIVIDUAL', 'MIXED', NULL, NULL),
('-41kg', 'INDIVIDUAL', 'WOMAN', 57, NULL),
('-45kg', 'INDIVIDUAL', 'WOMAN', 57, NULL),
('-50kg', 'INDIVIDUAL', 'WOMAN', 57, NULL),
('-55kg', 'INDIVIDUAL', 'WOMAN', 57, NULL),
('-61kg', 'INDIVIDUAL', 'WOMAN', 57, NULL),
('-67kg', 'INDIVIDUAL', 'WOMAN', 57, NULL),
('-73kg', 'INDIVIDUAL', 'WOMAN', 57, NULL),
('-79kg', 'INDIVIDUAL', 'WOMAN', 57, NULL),
('-86kg', 'INDIVIDUAL', 'WOMAN', 57, NULL),
('+86kg', 'INDIVIDUAL', 'WOMAN', 57, NULL),
('-49kg', 'INDIVIDUAL', 'MAN', 57, NULL),
('-54kg', 'INDIVIDUAL', 'MAN', 57, NULL),
('-59kg', 'INDIVIDUAL', 'MAN', 57, NULL),
('-65kg', 'INDIVIDUAL', 'MAN', 57, NULL),
('-72kg', 'INDIVIDUAL', 'MAN', 57, NULL),
('-80kg', 'INDIVIDUAL', 'MAN', 57, NULL),
('-88kg', 'INDIVIDUAL', 'MAN', 57, NULL),
('-97kg', 'INDIVIDUAL', 'MAN', 57, NULL),
('-107kg', 'INDIVIDUAL', 'MAN', 57, NULL),
('+107kg', 'INDIVIDUAL', 'MAN', 57, NULL),
('-48kg J1, J2.', 'INDIVIDUAL', 'WOMAN', 56, NULL),
('-57kg J1, J2.', 'INDIVIDUAL', 'WOMAN', 56, NULL),
('-70 kg J1, J2.', 'INDIVIDUAL', 'WOMAN', 56, NULL),
('+70 kg J1, J2.', 'INDIVIDUAL', 'WOMAN', 56, NULL),
('-60kg J1, J2.', 'INDIVIDUAL', 'MAN', 56, NULL),
('-73kg J1, J2.', 'INDIVIDUAL', 'MAN', 56, NULL),
('-90kg J1, J2.', 'INDIVIDUAL', 'MAN', 56, NULL),
('+90kg J1, J2.', 'INDIVIDUAL', 'MAN', 56, NULL),
('50m nage libre S4, S10, S11, S13', 'INDIVIDUAL', 'WOMAN', 59, 44),
('50m nage libre S4, S10, S11, S13', 'INDIVIDUAL', 'MAN', 59, 44),
('50m nage libre S6, S8', 'INDIVIDUAL', 'WOMAN', 59, 44),
('50m nage libre S3, S5, S7, S9', 'INDIVIDUAL', 'MAN', 59, 44),
('100m nage libre S3, S7, S9, S11', 'INDIVIDUAL', 'WOMAN', 59, 45),
('100m nage libre S4, S6, S8', 'INDIVIDUAL', 'MAN', 59, 45),
('100m nage libre S5, S10, S12', 'INDIVIDUAL', 'WOMAN', 59, 45),
('100m nage libre S5, S10, S12', 'INDIVIDUAL', 'MAN', 59, 45),
('200m nage libre S2, S3, S4', 'INDIVIDUAL', 'MAN', 59, 46),
('200m nage libre S5, S14', 'INDIVIDUAL', 'WOMAN', 59, 46),
('200m nage libre S5, S14', 'INDIVIDUAL', 'MAN', 59, 46),
('400m nage libre S10', 'INDIVIDUAL', 'WOMAN', 59, 47),
('400m nage libre S6, S7, S8, S9, S11, S13', 'INDIVIDUAL', 'WOMAN', 59, 47),
('400m nage libre S6, S7, S8, S9, S11, S13', 'INDIVIDUAL', 'MAN', 59, 47),
('50m dos S2, S3, S4, S5', 'INDIVIDUAL', 'WOMAN', 59, NULL),
('50m dos S2, S3, S4, S5', 'INDIVIDUAL', 'MAN', 59, NULL),
('50m dos S1', 'INDIVIDUAL', 'MAN', 59, NULL),
('100m dos S2, S6, S8, S9, S10, S11, S12, S13, S14', 'INDIVIDUAL', 'WOMAN', 59, 50),
('100m dos S2, S6, S8, S9, S10, S11, S12, S13, S14', 'INDIVIDUAL', 'MAN', 59, 50),
('100m dos S1, S7', 'INDIVIDUAL', 'MAN', 59, 50),
('50m brasse SB3', 'INDIVIDUAL', 'WOMAN', 59, NULL),
('50m brasse SB3', 'INDIVIDUAL', 'MAN', 59, NULL),
('50m brasse SB2', 'INDIVIDUAL', 'MAN', 59, NULL),
('100m brasse SB4, SB5, SB6, SB8, SB9, SB11, SB13, SB14', 'INDIVIDUAL', 'WOMAN', 59, 52),
('100m brasse SB4, SB5, SB6, SB8, SB9, SB11, SB13, SB14', 'INDIVIDUAL', 'MAN', 59, 52),
('100m brasse SB3', 'INDIVIDUAL', 'MAN', 59, 52),
('100m brasse SB7, SB12', 'INDIVIDUAL', 'WOMAN', 59, 52),
('50m papillon S5, S6, S7', 'INDIVIDUAL', 'WOMAN', 59, NULL),
('50m papillon S5, S6, S7', 'INDIVIDUAL', 'MAN', 59, NULL),
('100m papillon S8, S9, S10, S13, S14', 'INDIVIDUAL', 'WOMAN', 59, 54),
('100m papillon S8, S9, S10, S13, S14', 'INDIVIDUAL', 'MAN', 59, 54),
('100m papillon S11, S12', 'INDIVIDUAL', 'MAN', 59, 54),
('150m medley individuel SM3', 'INDIVIDUAL', 'MAN', 59, NULL),
('150m medley individuel SM4', 'INDIVIDUAL', 'WOMAN', 59, NULL),
('150m medley individuel SM4', 'INDIVIDUAL', 'MAN', 59, NULL),
('200m medley individuel SM6, SM7, SM8, SM9, SM10, SM11, SM13, SM14', 'INDIVIDUAL', 'WOMAN', 59, NULL),
('200m medley individuel SM6, SM7, SM8, SM9, SM10, SM11, SM13, SM14', 'INDIVIDUAL', 'MAN', 59, NULL),
('200m medley individuel SM5', 'INDIVIDUAL', 'WOMAN', 59, NULL),
('K44 -47kg', 'INDIVIDUAL', 'WOMAN', 61, NULL),
('K44 -52kg', 'INDIVIDUAL', 'WOMAN', 61, NULL),
('K44 -57kg', 'INDIVIDUAL', 'WOMAN', 61, NULL),
('K44 -65kg', 'INDIVIDUAL', 'WOMAN', 61, NULL),
('K44 +65kg', 'INDIVIDUAL', 'WOMAN', 61, NULL),
('K44 -58kg', 'INDIVIDUAL', 'MAN', 61, NULL),
('K44 -63kg', 'INDIVIDUAL', 'MAN', 61, NULL),
('K44 -70kg', 'INDIVIDUAL', 'MAN', 61, NULL),
('K44 -80kg', 'INDIVIDUAL', 'MAN', 61, NULL),
('K44 +80kg', 'INDIVIDUAL', 'MAN', 61, NULL),
('Simple classe 1, 2', 'INDIVIDUAL', 'MAN', 60, NULL),
('Simple classe 1-2', 'INDIVIDUAL', 'WOMAN', 60, NULL),
('Simple classe 3, 4, 5, 6, 7, 8, 9, 10, 11', 'INDIVIDUAL', 'WOMAN', 60, NULL),
('Simple classe 3, 4, 5, 6, 7, 8, 9, 10, 11', 'INDIVIDUAL', 'MAN', 60, NULL),
('Double MD4, MD8, MD14, MD18', 'COLLECTIVE', 'MAN', 60, NULL),
('Double WD5, WD10, WD14, WD20', 'COLLECTIVE', 'WOMAN', 60, NULL),
('Double XD7, XD17', 'COLLECTIVE', 'MIXED', 60, NULL),
('Individuel W1', 'INDIVIDUAL', 'WOMAN', NULL, NULL),
('Individuel W1', 'INDIVIDUAL', 'MAN', NULL, NULL),
('Individuel W1', 'COLLECTIVE', 'MIXED', NULL, NULL),
('R1 10m Carabine à air «Debout» SH1', 'INDIVIDUAL', 'MAN', 63, NULL),
('R2 10m Carabine à air «Debout» SH1', 'INDIVIDUAL', 'WOMAN', 63, NULL),
('R3 10m Carabine à air «Couché» SH1', 'INDIVIDUAL', 'MIXED', 63, NULL),
('R7 50m Carabine 3 Positions SH1', 'INDIVIDUAL', 'MAN', 63, NULL),
('R8 50m Carabine 3 Positions SH1', 'INDIVIDUAL', 'WOMAN', 63, NULL),
('R4 10m Carabine à air «Debout» SH2', 'INDIVIDUAL', 'MIXED', 63, NULL),
('R5 10m Carabine à air «Couché» SH2', 'INDIVIDUAL', 'MIXED', 63, NULL),
('R6 50m Carabine «Couché» SH1', 'INDIVIDUAL', 'MIXED', 63, NULL),
('R9 50m Carabine «Couché» SH2', 'INDIVIDUAL', 'MIXED', 63, NULL),
('P1 10m Pistolet à air SH1', 'INDIVIDUAL', 'MAN', 63, NULL),
('P2 10m Pistolet à air SH1', 'INDIVIDUAL', 'WOMAN', 63, NULL),
('Pistolet 25m SH1', 'INDIVIDUAL', 'MIXED', 63, NULL),
('P4 Pistolet 50m SH1', 'INDIVIDUAL', 'MIXED', 63, NULL),
('PTWC', 'INDIVIDUAL', 'WOMAN', 62, NULL),
('PTWC', 'INDIVIDUAL', 'MAN', 62, NULL),
('PTS2', 'INDIVIDUAL', 'WOMAN', 62, NULL),
('PTS2', 'INDIVIDUAL', 'MAN', 62, NULL),
('PTS3', 'INDIVIDUAL', 'MAN', 62, NULL),
('PTS4', 'INDIVIDUAL', 'WOMAN', 62, NULL),
('PTS4', 'INDIVIDUAL', 'MAN', 62, NULL),
('PTS5', 'INDIVIDUAL', 'WOMAN', 62, NULL),
('PTS5', 'INDIVIDUAL', 'MAN', 62, NULL),
('PTVI', 'INDIVIDUAL', 'WOMAN', 62, NULL),
('PTVI', 'INDIVIDUAL', 'MAN', 62, NULL),
('Tournoi 8 équipes', 'COLLECTIVE', 'MIXED', 67, NULL),
('Simple', 'INDIVIDUAL', 'WOMAN', 68, NULL),
('Simple', 'INDIVIDUAL', 'MAN', 68, NULL),
('Double', 'COLLECTIVE', 'WOMAN', 68, NULL),
('Double', 'COLLECTIVE', 'MAN', 68, NULL),
('Simple quad', 'INDIVIDUAL', 'MIXED', 68, NULL),
('Double quad', 'COLLECTIVE', 'MIXED', 68, NULL),
('Tournoi 8 équipes', 'COLLECTIVE', 'WOMAN', 64, NULL),
('Tournoi 8 équipes', 'COLLECTIVE', 'MAN', 64, NULL);
INSERT IGNORE INTO Is_from (id_athlete, code_country) VALUES
(0, 'JAM'),
(1, 'JAM'),
(2, 'USA'),
(3, 'ZAF'),
(4, 'KEN'),
(5, 'NOR'),
(6, 'ETH'),
(7, 'KEN'),
(8, 'CHN'),
(9, 'NOR'),
(10, 'KEN'),
(11, 'CHN'),
(12, 'AUS'),
(13, 'USA'),
(14, 'BRA'),
(15, 'USA'),
(16, 'LTU'),
(17, 'BLR'),
(18, 'NOR'),
(19, 'CAN'),
(20, 'USA'),
(21, 'FRA'),
(22, 'UKR'),
(23, 'KEN'),
(24, 'KEN'),
(25, 'ETH'),
(26, 'ETH'),
(27, 'PRI'),
(28, 'USA'),
(29, 'RUS'),
(30, 'CHN'),
(31, 'USA'),
(32, 'VEN'),
(33, 'RUS'),
(34, 'RUS'),
(35, 'DEU'),
(36, 'DEU'),
(37, 'POL'),
(38, 'CUB'),
(39, 'USA'),
(40, 'USA'),
(40, 'USA'),
(42, 'CHN'),
(43, 'UKR'),
(44, 'USA'),
(45, 'RUS'),
(46, 'GBR'),
(47, 'AUS'),
(48, 'SGP'),
(49, 'HUN'),
(50, 'AUS'),
(51, 'AUS'),
(52, 'USA'),
(53, 'AUS'),
(54, 'USA'),
(55, 'USA'),
(56, 'ZAF'),
(57, 'SWE'),
(58, 'CHN'),
(59, 'USA'),
(60, 'HUN');

INSERT IGNORE INTO Athlete (firstname_athlete, name_athlete, birthday_athlete, gender_athlete, code_country) VALUES
('Usain', 'Bolt', '1986-08-21', 'MAN', 'JAM'),
('Elaine', 'Thompson-Herah', '1992-06-28', 'WOMAN', 'JAM'),
('Bob', 'Beamon', '1946-08-29', 'MAN', 'USA'),
('Wayde', 'van Niekerk', '1992-07-15', 'MAN', 'ZAF'),
('David', 'Rudisha', '1988-12-17', 'MAN', 'KEN'),
('Jakob', 'Ingebrigtsen', '2000-09-19', 'MAN', 'NOR'),
('Kenenisa', 'Bekele', '1982-06-13', 'MAN', 'ETH'),
('Samuel', 'Wanjiru', '1986-11-10', 'MAN', 'KEN'),
('Liu', 'Xiang', '1983-07-13', 'MAN', 'CHN'),
('Karsten', 'Warholm', '1996-02-28', 'MAN', 'NOR'),
('Conseslus', 'Kipruto', '1994-12-08', 'MAN', 'KEN'),
('Chen', 'Ding', '1992-08-05', 'MAN', 'CHN'),
('Jared', 'Tallent', '1984-10-17', 'MAN', 'AUS'),
('Kenny', 'Harrison', '1965-02-13', 'MAN', 'USA'),
('Thiago', 'Braz da Silva', '1993-12-16', 'MAN', 'BRA'),
('Ryan', 'Crouser', '1992-12-18', 'MAN', 'USA'),
('Virgilijus', 'Alekna', '1972-02-13', 'MAN', 'LTU'),
('Sergey', 'Litvinov', '1992-12-18', 'MAN', 'BLR'),
('Andreas', 'Thorkildsen', '1982-04-01', 'MAN', 'NOR'),
('Damian', 'Warner', '1989-10-04', 'MAN', 'CAN'),
('Florence', 'Griffith-Joyner', '1959-12-21', 'WOMAN', 'USA'),
('Marie-José', 'Pérec', '1968-05-09', 'WOMAN', 'FRA'),
('Nadiya', 'Olizarenko', '1953-11-28', 'WOMAN', 'UKR'),
('Faith', 'Kipyegon', '1994-01-10', 'WOMAN', 'KEN'),
('Vivian', 'Cheruiyot', '1983-09-11', 'WOMAN', 'KEN'),
('Almaz', 'Ayana', '1991-11-21', 'WOMAN', 'ETH'),
('Tiki', 'Gelana', '1987-10-22', 'WOMAN', 'ETH'),
('Jasmine', 'Camacho-Quinn', '1996-08-21', 'WOMAN', 'PRI'),
('Sydney', 'McLaughlin', '1999-09-07', 'WOMAN', 'USA'),
('Gulnara', 'Samitova-Galkina', '1978-07-09', 'WOMAN', 'RUS'),
('Qieyang', 'Shenjie', '1990-11-11', 'WOMAN', 'CHN'),
('Jackie', 'Joyner-Kersee', '1962-03-03', 'WOMAN', 'USA'),
('Yulimar', 'Rojas', '1995-10-21', 'WOMAN', 'VEN'),
('Yelena', 'Slesarenko', '1982-02-28', 'WOMAN', 'RUS'),
('Yelena', 'Isinbayeva', '1982-06-03', 'WOMAN', 'RUS'),
('Ilona', 'Slupianek', '1956-09-24', 'WOMAN', 'DEU'),
('Martina', 'Hellmann', '1960-12-12', 'WOMAN', 'DEU'),
('Anita', 'Włodarczyk', '1985-08-08', 'WOMAN', 'POL'),
('Olisdeilys', 'Menéndez', '1979-11-14', 'WOMAN', 'CUB'),
('Caeleb', 'Dressel', '1996-08-16', 'MAN', 'USA'),
('Michael', 'Phelps', '1985-06-30', 'MAN', 'USA'),
('Michael', 'Phelps', '1985-06-30', 'MAN', 'USA'),
('Sun', 'Yang', '1991-12-01', 'MAN', 'CHN'),
('Mykhailo', 'Romanchuk', '1996-08-07', 'MAN', 'UKR'),
('Ryan', 'Murphy', '1965-11-09', 'MAN', 'USA'),
('Evgeny', 'Rylov', '1996-09-23', 'MAN', 'RUS'),
('Adam', 'Peaty', '1994-12-28', 'MAN', 'GBR'),
('Zac', 'Stubblety-Cook', '1999-01-04', 'MAN', 'AUS'),
('Joseph', 'Schooling', '1995-06-16', 'MAN', 'SGP'),
('Kristóf', 'Milák', '2000-02-20', 'MAN', 'HUN'),
('Emma', 'McKeon', '1994-05-24', 'WOMAN', 'AUS'),
('Ariarne', 'Titmus', '2000-09-07', 'WOMAN', 'AUS'),
('Katie', 'Ledecky', '1997-03-17', 'WOMAN', 'USA'),
('Kaylee', 'McKeown', '2001-07-11', 'WOMAN', 'AUS'),
('Missy', 'Franklin', '1995-05-10', 'WOMAN', 'USA'),
('Lilly', 'King', '1997-02-10', 'WOMAN', 'USA'),
('Tatjana', 'Schoenmaker', '1997-07-09', 'WOMAN', 'ZAF'),
('Sarah', 'Sjöström', '1993-08-17', 'WOMAN', 'SWE'),
('Zhang', 'Yufei', '1998-04-19', 'WOMAN', 'CHN'),
('Charles', 'Austin', '1967-12-19', 'MAN', 'USA'),
('Katinka', 'Hosszú', '1985-05-03', 'WOMAN', 'HUN');