INSERT INTO Transport (name_trans) VALUES
('TRAIN'),
('TRAMWAY'),
('BUS'),
('METRO');
INSERT INTO Site (name_site, adress_site, creation_date_site, capacity_site, URL_site) VALUES
 ('Seine', 'Seine', NULL, 600000, 'https://fr.wikipedia.org//wiki/Seine_%C3%A0_Paris'),
 ('Stade de France', 'ZAC du Cornillon Nord93200 Saint-Denis,  France', '1995-00-00', 77083, 'https://fr.wikipedia.org//wiki/Stade_de_France'),
 ('Village olympique de Saint-Denis', 'Village olympique de Saint-Denis', NULL, NULL, 'https://fr.wikipedia.org//wiki/Village_olympique_de_Saint-Denis'),
 ('Centre aquatique', 'Avenue du Président-Wilson, Saint-Denis', '2024-00-00', 5000, 'https://fr.wikipedia.org//wiki/Piscine_olympique_de_Saint-Denis'),
 ('Stade Tour Eiffel(Champ-de-Mars)', 'Stade Tour Eiffel(Champ-de-Mars)', '1770-00-00', 12860, 'https://fr.wikipedia.org//wiki/Champ-de-Mars_(Paris)'),
 ('Pont Alexandre-III[S 1] et Seine (nage)', 'Pont Alexandre-III[S 1] et Seine (nage)', NULL, 1000, 'https://fr.wikipedia.org//wiki/Pont_Alexandre-III'),
 ('Grand Palais', 'Grand Palais', '1900-00-00', 8000, 'https://fr.wikipedia.org//wiki/Grand_Palais_(Paris)'),
 ('Arena Champ-de-Mars(Grand Palais éphémère)', 'Arena Champ-de-Mars(Grand Palais éphémère)', '2021-06-12', 8356, 'https://fr.wikipedia.org//wiki/Grand_Palais_%C3%A9ph%C3%A9m%C3%A8re'),
 ('Esplanade des Invalides', 'Esplanade des Invalides', '1704-00-00', 8000, 'https://fr.wikipedia.org//wiki/Esplanade_des_Invalides'),
 ('Arena Paris Sud(Parc des expositions de la porte de Versailles)', '1 place de la Porte-de-Versailles 15e arrondissement de Paris, Paris France', NULL, 6650, 'https://fr.wikipedia.org//wiki/Paris_Expo_Porte_de_Versailles'),
 ('Parc des Princes', '24 rue du Commandant-Guilbaud[1] 75016 Paris, France', '1967-07-08', 47926, 'https://fr.wikipedia.org//wiki/Parc_des_Princes'),
 ('Stade Roland-Garros', '3 avenue Gordon-Bennett  75016, France', '1928-00-00', 14962, 'https://fr.wikipedia.org//wiki/Stade_Roland-Garros'),
 ('Palais omnisports de Paris-Bercy[S 4]', '8, boulevard de Bercy, Paris 12e', '1984-02-03', 15000, 'https://fr.wikipedia.org//wiki/Palais_omnisports_de_Paris-Bercy'),
 ('Arena Porte de la Chapelle[60]', '58 boulevard Ney 18e arrondissement de Paris, Paris France', '2024-02-11', 7000, 'https://fr.wikipedia.org//wiki/Arena_Porte_de_la_Chapelle'),
 ('Paris La Défense Arena[S 4]', '99 Jardins de l'ArcheNanterre France', '2013-12-02', 17000, 'https://fr.wikipedia.org//wiki/Paris_La_D%C3%A9fense_Arena'),
 ('Stade Yves-du-Manoir', '12, rue François-Faber92700 Colombes', '1907-00-00', 15000, 'https://fr.wikipedia.org//wiki/Stade_d%C3%A9partemental_Yves-du-Manoir'),
 ('Base nautique de Vaires-sur-Marne', 'Base nautique de Vaires-sur-Marne', '1980-00-00', 24000, 'https://fr.wikipedia.org//wiki/%C3%8Ele_de_loisirs_de_Vaires-Torcy'),
 ('Château de Versailles', 'Château de Versailles', NULL, 40000, 'https://fr.wikipedia.org//wiki/Ch%C3%A2teau_de_Versailles'),
 ('Vélodrome national', '1, rue Laurent FignonMontigny-le-Bretonneux', '2011-10-03', 5000, 'https://fr.wikipedia.org//wiki/V%C3%A9lodrome_de_Saint-Quentin-en-Yvelines'),
 ('Colline d'Élancourt', 'Colline d'Élancourt', NULL, 15000, 'https://fr.wikipedia.org//wiki/Colline_d%27%C3%89lancourt'),
 ('Golf national', 'Golf national', NULL, 32720, 'https://fr.wikipedia.org//wiki/Golf_national'),
 ('Marina olympique du Roucas-Blanc[S 5]', '6 Prom. Georges Pompidou, 13008 Marseille', NULL, 12262, 'https://fr.wikipedia.org//wiki/Marina_olympique_du_Roucas-Blanc'),
 ('Teahupo'o[29]', 'Teahupo'o[29]', NULL, 600, 'https://fr.wikipedia.org//wiki/Teahupo%27o'),
 ('Stade de Bordeaux[S 4]', 'Cours Jules-Ladoumègue 33300 Bordeaux, France', '2012-00-00', 42000, 'https://fr.wikipedia.org//wiki/Matmut_Atlantique'),
 ('Stade Pierre-Mauroy', '261 Boulevard de Tournai 59650 Villeneuve-d'Ascq, France', '2024-09-27', 27000, 'https://fr.wikipedia.org//wiki/Stade_Pierre-Mauroy'),
 ('Parc Olympique lyonnais[S 4]', '10 avenue Simone-Veil 69150 Décines-Charpieu, France', '2012-10-22', 59186, 'https://fr.wikipedia.org//wiki/Parc_Olympique_lyonnais'),
 ('Stade Vélodrome[S 4]', '3 boulevard Michelet 13008 Marseille, France', '1935-04-28', 67394, 'https://fr.wikipedia.org//wiki/Stade_V%C3%A9lodrome'),
 ('Stade de la Beaujoire', '5 boulevard de la Beaujoire 44300 Nantes', '1984-05-08', 37473, 'https://fr.wikipedia.org//wiki/Stade_de_la_Beaujoire'),
 ('Stade Riviera[S 4]', 'Boulevard des Jardiniers06200 Nice  France', '2011-08-06', 36178, 'https://fr.wikipedia.org//wiki/Allianz_Riviera'),
 ('Stade Geoffroy-Guichard', '14, rue Paul et Pierre Guichard42000 Saint-Étienne', '1930-09-00', 41965, 'https://fr.wikipedia.org//wiki/Stade_Geoffroy-Guichard'),
 ('Site d'escalade du Bourget', '9 rue Roger Salengro, 93350, Le Bourget', '2020-00-00', 6000, 'https://fr.wikipedia.org//wiki/Site_d%27escalade_du_Bourget'),
 ('Parc des expositions du Bourget', 'Le Bourget, Seine-Saint-Denis, France', NULL, NULL, 'https://fr.wikipedia.org//wiki/Parc_des_expositions_de_Paris-Le_Bourget'),
 ('Place de la Concorde[29]', 'Place de la Concorde[29]', '1763-00-00', NULL, 'https://fr.wikipedia.org//wiki/Place_de_la_Concorde'),
 ('Arena Paris Nord', 'Villepinte, Seine-Saint-Denis France', '1982-12-00', 6000, 'https://fr.wikipedia.org//wiki/Parc_des_expositions_de_Paris-Nord_Villepinte'),
 ('Centre national de tir sportif', 'Route de Lignières, RD 925, 36130 Déols,  France', '2018-00-00', NULL, 'https://fr.wikipedia.org//wiki/Centre_national_de_tir_sportif');
INSERT INTO To_Serve (id_site, id_trans, num_ligne, station_name) VALUES
 (None, 1, 'RER A', 'Gare de Lyon'),
 (None, 1, 'RER D', 'Gare de Lyon'),
 (None, 1, 'Train R', 'Gare de Lyon'),
 (None, 4, 'Métro 1', 'Gare de Lyon'),
 (5, 4, 'Métro 10', 'Ségur'),
 (10, 1, 'RER B', 'Parc des expositions'),
 (10, 2, 'Tramway T3a', 'Georges Brassens'),
 (8, 1, 'RER E', 'Rosa Parks'),
 (4, 4, 'Métro 14', 'Pleyel'),
 (None, 1, 'Train L depuis la gare Saint-Lazare à Paris', 'Versailles Rive Droite'),
 (20, 1, 'RER C', 'Saint-Quentin-en-Yvelines'),
 (20, 1, 'Train N depuis la gare Montparnasse à Paris', 'Saint-Quentin-en-Yvelines'),
 (20, 1, 'Train U depuis la gare de La Défense', 'Saint-Quentin-en-Yvelines'),
 (7, 1, 'RER C', 'Invalides'),
 (7, 4, 'Métro 8', 'Invalides'),
 (7, 4, 'Métro 13', 'Invalides'),
 (None, 4, 'Métro 12', 'Assemblée Nationale'),
 (33, 4, 'Franklin D. Roosevelt »', 'Franklin D. Roosevelt'),
 (21, 1, 'RER C', 'Saint-Quentin-en-Yvelines'),
 (21, 1, 'Train N depuis la gare Montparnasse à Paris', 'Saint-Quentin-en-Yvelines'),
 (21, 1, 'Train U depuis la gare de La Défense', 'Saint-Quentin-en-Yvelines'),
 (None, 4, 'Ligne 83', 'Plage Roucas Blanc'),
 (11, 4, 'Métro 9', 'Marcel Sembat'),
 (11, 4, 'Métro 10', 'Porte d’Auteuil'),
 (11, 4, 'Métro 9', 'Porte de Saint-Cloud'),
 (11, 1, 'RER C', 'Pont du Garigliano'),
 (11, 1, 'RER A', 'Charles-de-Gaulle – Etoile'),
 (11, 4, 'Métro 1', 'Charles-de-Gaulle – Etoile'),
 (11, 4, 'Métro 2', 'Charles-de-Gaulle – Etoile'),
 (11, 4, 'Métro 6', 'Charles-de-Gaulle – Etoile'),
 (8, 1, 'RER A', 'Nanterre Préfecture'),
 (6, 1, 'RER C', 'Invalides'),
 (6, 4, 'Métro 8', 'Invalides'),
 (6, 4, 'Métro 13', 'Invalides'),
 (31, 1, 'RER B', 'Le Bourget'),
 (31, 2, 'Tramway T11', 'Le Bourget'),
 (24, 4, 'Ligne B', 'La Cité du Vin'),
 (2, 1, 'Train H depuis la gare du Nord à Paris', 'Saint-Denis'),
 (None, 4, 'Ligne M2', 'Sainte-Marguerite Dromel'),
 (12, 4, 'Métro 10', 'Porte d’Auteuil'),
 (5, 4, 'Métro 9', 'Alma Marceau'),
 (None, 1, 'RER C', 'Pont de l’Alma'),
INSERT INTO To_Serve (id_site, id_trans, num_ligne, station_name) VALUES
 (None, 1, 'RER A', 'Gare de Lyon'),
 (None, 1, 'RER D', 'Gare de Lyon'),
 (None, 1, 'Train R', 'Gare de Lyon'),
 (None, 4, 'Métro 1', 'Gare de Lyon'),
 (5, 4, 'Métro 10', 'Ségur'),
 (10, 1, 'RER B', 'Parc des expositions'),
 (10, 2, 'Tramway T3a', 'Georges Brassens'),
 (8, 1, 'RER E', 'Rosa Parks'),
 (4, 4, 'Métro 14', 'Pleyel'),
 (None, 1, 'Train L depuis la gare Saint-Lazare à Paris', 'Versailles Rive Droite'),
 (20, 1, 'RER C', 'Saint-Quentin-en-Yvelines'),
 (20, 1, 'Train N depuis la gare Montparnasse à Paris', 'Saint-Quentin-en-Yvelines'),
 (20, 1, 'Train U depuis la gare de La Défense', 'Saint-Quentin-en-Yvelines'),
 (7, 1, 'RER C', 'Invalides'),
 (7, 4, 'Métro 8', 'Invalides'),
 (7, 4, 'Métro 13', 'Invalides'),
 (None, 4, 'Métro 12', 'Assemblée Nationale'),
 (33, 4, 'Franklin D. Roosevelt »', 'Franklin D. Roosevelt'),
 (21, 1, 'RER C', 'Saint-Quentin-en-Yvelines'),
 (21, 1, 'Train N depuis la gare Montparnasse à Paris', 'Saint-Quentin-en-Yvelines'),
 (21, 1, 'Train U depuis la gare de La Défense', 'Saint-Quentin-en-Yvelines'),
 (None, 4, 'Ligne 83', 'Plage Roucas Blanc'),
 (11, 4, 'Métro 9', 'Marcel Sembat'),
 (11, 4, 'Métro 10', 'Porte d’Auteuil'),
 (11, 4, 'Métro 9', 'Porte de Saint-Cloud'),
 (11, 1, 'RER C', 'Pont du Garigliano'),
 (11, 1, 'RER A', 'Charles-de-Gaulle – Etoile'),
 (11, 4, 'Métro 1', 'Charles-de-Gaulle – Etoile'),
 (11, 4, 'Métro 2', 'Charles-de-Gaulle – Etoile'),
 (11, 4, 'Métro 6', 'Charles-de-Gaulle – Etoile'),
 (8, 1, 'RER A', 'Nanterre Préfecture'),
 (6, 1, 'RER C', 'Invalides'),
 (6, 4, 'Métro 8', 'Invalides'),
 (6, 4, 'Métro 13', 'Invalides'),
 (31, 1, 'RER B', 'Le Bourget'),
 (31, 2, 'Tramway T11', 'Le Bourget'),
 (24, 4, 'Ligne B', 'La Cité du Vin'),
 (2, 1, 'Train H depuis la gare du Nord à Paris', 'Saint-Denis'),
 (None, 4, 'Ligne M2', 'Sainte-Marguerite Dromel'),
 (12, 4, 'Métro 10', 'Porte d’Auteuil'),
 (5, 4, 'Métro 9', 'Alma Marceau'),
 (None, 1, 'RER C', 'Pont de l’Alma');
INSERT INTO Athlete (firstname_athlete, name_athlete, birthday_athlete, gender_athlete, code_country) VALUES
('Usain', 'Bolt', '1986-08-21', Homme', JAM'),
('Elaine', 'Thompson-Herah', '1992-06-28', Femme', JAM'),
('Bob', 'Beamon', '1946-08-29', Homme', USA'),
('Wayde', 'van Niekerk', '1992-07-15', Homme', ZAF'),
('David', 'Rudisha', '1988-12-17', Homme', KEN'),
('Jakob', 'Ingebrigtsen', '2000-09-19', Homme', NOR'),
('Kenenisa', 'Bekele', '1982-06-13', Homme', ETH'),
('Samuel', 'Wanjiru', '1986-11-10', Homme', KEN'),
('Liu', 'Xiang', '1983-07-13', Homme', CHN'),
('Karsten', 'Warholm', '1996-02-28', Homme', NOR'),
('Conseslus', 'Kipruto', '1994-12-08', Homme', KEN'),
('Chen', 'Ding', '1992-08-05', Homme', CHN'),
('Jared', 'Tallent', '1984-10-17', Homme', AUS'),
('Kenny', 'Harrison', '1965-02-13', Homme', USA'),
('Thiago', 'Braz da Silva', '1993-12-16', Homme', BRA'),
('Ryan', 'Crouser', '1992-12-18', Homme', USA'),
('Virgilijus', 'Alekna', '1972-02-13', Homme', LTU'),
('Sergey', 'Litvinov', '1992-12-18', Homme', BLR'),
('Andreas', 'Thorkildsen', '1982-04-01', Homme', NOR'),
('Damian', 'Warner', '1989-10-04', Homme', CAN'),
('Florence', 'Griffith-Joyner', '1959-12-21', Femme', USA'),
('Marie-José', 'Pérec', '1968-05-09', Femme', FRA'),
('Nadiya', 'Olizarenko', '1953-11-28', Femme', UKR'),
('Faith', 'Kipyegon', '1994-01-10', Femme', KEN'),
('Vivian', 'Cheruiyot', '1983-09-11', Femme', KEN'),
('Almaz', 'Ayana', '1991-11-21', Femme', ETH'),
('Tiki', 'Gelana', '1987-10-22', Femme', ETH'),
('Jasmine', 'Camacho-Quinn', '1996-08-21', Femme', PRI'),
('Sydney', 'McLaughlin', '1999-09-07', Femme', USA'),
('Gulnara', 'Samitova-Galkina', '1978-07-09', Femme', RUS'),
('Qieyang', 'Shenjie', '1990-11-11', Femme', CHN'),
('Jackie', 'Joyner-Kersee', '1962-03-03', Femme', USA'),
('Yulimar', 'Rojas', '1995-10-21', Femme', VEN'),
('Yelena', 'Slesarenko', '1982-02-28', Femme', RUS'),
('Yelena', 'Isinbayeva', '1982-06-03', Femme', RUS'),
('Ilona', 'Slupianek', '1956-09-24', Femme', DEU'),
('Martina', 'Hellmann', '1960-12-12', Femme', DEU'),
('Anita', 'Włodarczyk', '1985-08-08', Femme', POL'),
('Olisdeilys', 'Menéndez', '1979-11-14', Femme', CUB'),
('Caeleb', 'Dressel', '1996-08-16', Homme', USA'),
('Michael', 'Phelps', '1985-06-30', Homme', USA'),
('Michael', 'Phelps', '1985-06-30', Homme', USA'),
('Sun', 'Yang', '1991-12-01', Homme', CHN'),
('Mykhailo', 'Romanchuk', '1996-08-07', Homme', UKR'),
('Ryan', 'Murphy', '1965-11-09', Homme', USA'),
('Evgeny', 'Rylov', '1996-09-23', Homme', RUS'),
('Adam', 'Peaty', '1994-12-28', Homme', GBR'),
('Zac', 'Stubblety-Cook', '1999-01-04', Homme', AUS'),
('Joseph', 'Schooling', '1995-06-16', Homme', SGP'),
('Kristóf', 'Milák', '2000-02-20', Homme', HUN'),
('Emma', 'McKeon', '1994-05-24', Femme', AUS'),
('Ariarne', 'Titmus', '2000-09-07', Femme', AUS'),
('Katie', 'Ledecky', '1997-03-17', Femme', USA'),
('Kaylee', 'McKeown', '2001-07-11', Femme', AUS'),
('Missy', 'Franklin', '1995-05-10', Femme', USA'),
('Lilly', 'King', '1997-02-10', Femme', USA'),
('Tatjana', 'Schoenmaker', '1997-07-09', Femme', ZAF'),
('Sarah', 'Sjöström', '1993-08-17', Femme', SWE'),
('Zhang', 'Yufei', '1998-04-19', Femme', CHN'),
('Katinka', 'Hosszú', '1985-05-03', Femme', HUN');
INSERT INTO Country (code_country, name_country) VALUES
('AFG', ' Afghanistan'),
('ZAF', ' Afrique du Sud'),
('ALA', ' Îles Åland'),
('ALB', ' Albanie'),
('DZA', ' Algérie'),
('DEU', ' Allemagne'),
('AND', ' Andorre'),
('AGO', ' Angola'),
('AIA', ' Anguilla'),
('ATA', ' Antarctique'),
('ATG', ' Antigua-et-Barbuda'),
('SAU', ' Arabie saoudite'),
('ARG', ' Argentine'),
('ARM', ' Arménie'),
('ABW', ' Aruba'),
('AUS', ' Australie'),
('AUT', ' Autriche'),
('AZE', ' Azerbaïdjan'),
('BHS', ' Bahamas'),
('BHR', ' Bahreïn'),
('BGD', ' Bangladesh'),
('BRB', ' Barbade'),
('BLR', ' Biélorussie'),
('BEL', ' Belgique'),
('BLZ', ' Belize'),
('BEN', ' Bénin'),
('BMU', ' Bermudes'),
('BTN', ' Bhoutan'),
('BOL', ' Bolivie'),
('BES', ' Pays-Bas caribéens'),
('BIH', ' Bosnie-Herzégovine'),
('BWA', ' Botswana'),
('BVT', ' Île Bouvet'),
('BRA', ' Brésil'),
('BRN', ' Brunei'),
('BGR', ' Bulgarie'),
('BFA', ' Burkina Faso'),
('BDI', ' Burundi'),
('CYM', ' Îles Caïmans'),
('KHM', ' Cambodge'),
('CMR', ' Cameroun'),
('CAN', ' Canada'),
('CPV', ' Cap-Vert'),
('CAF', ' République centrafricaine'),
('CHL', ' Chili'),
('CHN', ' Chine'),
('CXR', ' Île Christmas'),
('CYP', ' Chypre'),
('CCK', ' Îles Cocos'),
('COL', ' Colombie'),
('COM', ' Comores'),
('COG', ' République du Congo'),
('COD', ' République démocratique du Congo'),
('COK', ' Îles Cook'),
('KOR', ' Corée du Sud'),
('PRK', ' Corée du Nord'),
('CRI', ' Costa Rica'),
('CIV', ' Côte d'Ivoire'),
('HRV', ' Croatie'),
('CUB', ' Cuba'),
('CUW', ' Curaçao'),
('DNK', ' Danemark'),
('DJI', ' Djibouti'),
('DOM', ' République dominicaine'),
('DMA', ' Dominique'),
('EGY', ' Égypte'),
('ARE', ' Émirats arabes unis'),
('ECU', ' Équateur'),
('ERI', ' Érythrée'),
('ESP', ' Espagne'),
('EST', ' Estonie'),
('USA', ' États-Unis'),
('ETH', ' Éthiopie'),
('FLK', ' Malouines'),
('FRO', ' Îles Féroé'),
('FJI', ' Fidji'),
('FIN', ' Finlande'),
('FRA', ' France'),
('GAB', ' Gabon'),
('GMB', ' Gambie'),
('GEO', ' Géorgie'),
('SGS', ' Géorgie du Sud-et-les îles Sandwich du Sud'),
('GHA', ' Ghana'),
('GIB', ' Gibraltar'),
('GRC', ' Grèce'),
('GRD', ' Grenade'),
('GRL', ' Groenland'),
('GLP', ' Guadeloupe'),
('GUM', ' Guam'),
('GTM', ' Guatemala'),
('GGY', ' Guernesey'),
('GIN', ' Guinée'),
('GNB', ' Guinée-Bissau'),
('GNQ', ' Guinée équatoriale'),
('GUY', ' Guyana'),
('GUF', ' Guyane'),
('HTI', ' Haïti'),
('HMD', ' Îles Heard-et-MacDonald'),
('HND', ' Honduras'),
('HKG', ' Hong Kong'),
('HUN', ' Hongrie'),
('UMI', ' Îles mineures éloignées des États-Unis'),
('IND', ' Inde'),
('IDN', ' Indonésie'),
('IRN', ' Iran'),
('IRQ', ' Irak'),
('IRL', ' Irlande'),
('ISL', ' Islande'),
('ISR', ' Israël'),
('ITA', ' Italie'),
('JAM', ' Jamaïque'),
('JPN', ' Japon'),
('JEY', ' Jersey'),
('JOR', ' Jordanie'),
('KAZ', ' Kazakhstan'),
('KEN', ' Kenya'),
('KGZ', ' Kirghizistan'),
('KIR', ' Kiribati'),
('KWT', ' Koweït'),
('LAO', ' Laos'),
('LSO', ' Lesotho'),
('LVA', ' Lettonie'),
('LBN', ' Liban'),
('LBR', ' Liberia'),
('LBY', ' Libye'),
('LIE', ' Liechtenstein'),
('LTU', ' Lituanie'),
('LUX', ' Luxembourg'),
('MAC', ' Macao'),
('MKD', ' Macédoine du Nord'),
('MDG', ' Madagascar'),
('MYS', ' Malaisie'),
('MWI', ' Malawi'),
('MDV', ' Maldives'),
('MLI', ' Mali'),
('MLT', ' Malte'),
('IMN', ' Île de Man'),
('MNP', ' Îles Mariannes du Nord'),
('MAR', ' Maroc'),
('MHL', ' Îles Marshall'),
('MTQ', ' Martinique'),
('MUS', ' Maurice'),
('MRT', ' Mauritanie'),
('MYT', ' Mayotte'),
('MEX', ' Mexique'),
('FSM', ' États fédérés de Micronésie'),
('MDA', ' Moldavie'),
('MCO', ' Monaco'),
('MNG', ' Mongolie'),
('MNE', ' Monténégro'),
('MSR', ' Montserrat'),
('MOZ', ' Mozambique'),
('MMR', ' Birmanie'),
('NAM', ' Namibie'),
('NRU', ' Nauru'),
('NPL', ' Népal'),
('NIC', ' Nicaragua'),
('NER', ' Niger'),
('NGA', ' Nigeria'),
('NIU', ' Niue'),
('NFK', ' Île Norfolk'),
('NOR', ' Norvège'),
('NCL', ' Nouvelle-Calédonie'),
('NZL', ' Nouvelle-Zélande'),
('IOT', ' Territoire britannique de l'océan Indien'),
('OMN', ' Oman'),
('UGA', ' Ouganda'),
('UZB', ' Ouzbékistan'),
('PAK', ' Pakistan'),
('PLW', ' Palaos'),
('PSE', ' Palestine'),
('PAN', ' Panama'),
('PNG', ' Papouasie-Nouvelle-Guinée'),
('PRY', ' Paraguay'),
('NLD', ' Pays-Bas'),
('PER', ' Pérou'),
('PHL', ' Philippines'),
('PCN', ' Îles Pitcairn'),
('POL', ' Pologne'),
('PYF', ' Polynésie française'),
('PRI', ' Porto Rico'),
('PRT', ' Portugal'),
('QAT', ' Qatar'),
('REU', ' La Réunion'),
('ROU', ' Roumanie'),
('GBR', ' Royaume-Uni'),
('RUS', ' Russie'),
('RWA', ' Rwanda'),
('ESH', ' République arabe sahraouie démocratique'),
('BLM', ' Saint-Barthélemy'),
('KNA', ' Saint-Christophe-et-Niévès'),
('SMR', ' Saint-Marin'),
('MAF', ' Saint-Martin'),
('SXM', ' Saint-Martin'),
('SPM', ' Saint-Pierre-et-Miquelon'),
('VAT', ' Saint-Siège (État de la Cité du Vatican)'),
('VCT', ' Saint-Vincent-et-les-Grenadines'),
('SHN', ' Sainte-Hélène, Ascension et Tristan da Cunha'),
('LCA', ' Sainte-Lucie'),
('SLB', ' Îles Salomon'),
('SLV', ' Salvador'),
('WSM', ' Samoa'),
('ASM', ' Samoa américaines'),
('STP', ' Sao Tomé-et-Principe'),
('SEN', ' Sénégal'),
('SRB', ' Serbie'),
('SYC', ' Seychelles'),
('SLE', ' Sierra Leone'),
('SGP', ' Singapour'),
('SVK', ' Slovaquie'),
('SVN', ' Slovénie'),
('SOM', ' Somalie'),
('SDN', ' Soudan'),
('SSD', ' Soudan du Sud'),
('LKA', ' Sri Lanka'),
('SWE', ' Suède'),
('CHE', ' Suisse'),
('SUR', ' Suriname'),
('SJM', ' Svalbard et île Jan Mayen'),
('SWZ', ' Eswatini'),
('SYR', ' Syrie'),
('TJK', ' Tadjikistan'),
('TWN', ' Taïwan / (République de Chine (Taïwan))'),
('TZA', ' Tanzanie'),
('TCD', ' Tchad'),
('CZE', ' Tchéquie'),
('ATF', ' Terres australes et antarctiques françaises'),
('THA', ' Thaïlande'),
('TLS', ' Timor oriental'),
('TGO', ' Togo'),
('TKL', ' Tokelau'),
('TON', ' Tonga'),
('TTO', ' Trinité-et-Tobago'),
('TUN', ' Tunisie'),
('TKM', ' Turkménistan'),
('TCA', ' Îles Turques-et-Caïques'),
('TUR', ' Turquie'),
('TUV', ' Tuvalu'),
('UKR', ' Ukraine'),
('URY', ' Uruguay'),
('VUT', ' Vanuatu'),
('VEN', ' Venezuela'),
('VGB', ' Îles Vierges britanniques'),
('VIR', ' Îles Vierges des États-Unis'),
('VNM', ' Viêt Nam'),
('WLF', ' Wallis-et-Futuna'),
('YEM', ' Yémen'),
('ZMB', ' Zambie'),
('ZWE', ' Zimbabwe');
INSERT INTO Discipline (name_fr_disc, name_an_disc, category_disc) VALUES
('tir à l’arc', 'archery', 'Olympic'),
('athlétisme', 'athletics', 'Olympic'),
('badminton', 'badminton', 'Olympic'),
('basketball', 'basketball', 'Olympic'),
('basketball 3×3', 'basketball 3×3', 'Olympic'),
('boxe', 'boxing', 'Olympic'),
('canoë-kayak slalom', 'canoe slalom', 'Olympic'),
('canoë sprint', 'canoe sprint', 'Olympic'),
('cyclisme sur route', 'road cycling', 'Olympic'),
('cyclisme sur piste', 'cycling track', 'Olympic'),
('mountain bike (vtt)', 'mountain bike', 'Olympic'),
('bmx freestyle', 'bmx freestyle', 'Olympic'),
('bmx racing', 'bmx racing', 'Olympic'),
('sports équestres', 'equestrian', 'Olympic'),
('escrime', 'fencing', 'Olympic'),
('football', 'football', 'Olympic'),
('golf', 'golf', 'Olympic'),
('gymnastique artistique', 'artistic gymnastics', 'Olympic'),
('gymnastique rythmique', 'rhythmic gymnastics', 'Olympic'),
('trampoline', 'trampoline', 'Olympic'),
('handball', 'handball', 'Olympic'),
('hockey', 'hockey', 'Olympic'),
('judo', 'judo', 'Olympic'),
('pentathlon moderne', 'modern pentathlon', 'Olympic'),
('aviron', 'rowing', 'Olympic'),
('rugby', 'rugby', 'Olympic'),
('voile', 'sailing', 'Olympic'),
('tir', 'shooting', 'Olympic'),
('tennis de table', 'table tennis', 'Olympic'),
('taekwondo', 'taekwondo', 'Olympic'),
('taekwondo', 'tennis', 'Olympic'),
('triathlon', 'triathlon', 'Olympic'),
('volleyball', 'volleyball', 'Olympic'),
('volleyball de plage', 'beach volleyball', 'Olympic'),
('plongeon', 'diving', 'Olympic'),
('natation marathon', 'marathon swimming', 'Olympic'),
('natation artistique', 'artistic swimming', 'Olympic'),
('natation', 'swimming', 'Olympic'),
('waterpolo', 'water polo', 'Olympic'),
('haltérophilie', 'weightlifting', 'Olympic'),
('lutte', 'wrestling', 'Olympic'),
('breaking', 'breaking', 'Olympic'),
('escalade sportive', 'sport climbing', 'Olympic'),
('skateboard', 'skateboarding', 'Olympic'),
('surf', 'surfing', 'Olympic'),
('cécifoot', 'blind football', 'Paralympic'),
('boccia', 'boccia', 'Paralympic'),
('goalball', 'goalball', 'Paralympic'),
('para tir à l’arc', 'para archery', 'Paralympic'),
('para athlétisme', 'para athletics', 'Paralympic'),
('para badminton', 'para badminton', 'Paralympic'),
('para canoë', 'para canoe', 'Paralympic'),
('para cyclisme sur route', 'para cycling road', 'Paralympic'),
('para cyclisme sur piste', 'para cycling track', 'Paralympic'),
('para équitation (dressage)', 'para equestrian (para dressage)', 'Paralympic'),
('para judo', 'para judo', 'Paralympic'),
('para powerlifting', 'para powerlifting', 'Paralympic'),
('para aviron', 'para rowing', 'Paralympic'),
('para natation', 'para swimming', 'Paralympic'),
('para tennis de table', 'para table tennis', 'Paralympic'),
('para taekwondo', 'para taekwondo', 'Paralympic'),
('para triathlon', 'para triathlon', 'Paralympic'),
('para tir sportif', 'shooting para sport', 'Paralympic'),
('volleyball assis', 'sitting volleyball', 'Paralympic'),
('basket fauteuil', 'wheelchair basketball', 'Paralympic'),
('escrime fauteuil', 'wheelchair fencing', 'Paralympic'),
('rugby fauteuil', 'wheelchair rugby', 'Paralympic'),
('tennis fauteuil', 'wheelchair tennis', 'Paralympic');
INSERT INTO Record (stat_record, date_record, id_event, id_athlete) VALUES
('9 s 63', '2012-08-05', 'NULL', NULL'),
('19 s 30', '2008-08-20', 'NULL', NULL'),
('43 s 03', '2016-08-15', 'NULL', NULL'),
('1 min 40 s 91', '2012-08-09', 'NULL', NULL'),
('3 min 28 s 32', '2021-08-07', 'NULL', NULL'),
('12 min 57 s 82', '2008-08-23', 'NULL', NULL'),
('27 min 1 s 17', '2008-08-17', 'NULL', NULL'),
('2 h 6 min 32 s', '2008-08-24', 'NULL', NULL'),
('12 s 91', '2004-08-27', 'NULL', NULL'),
('45 s 94', '2021-08-03', 'NULL', NULL'),
('8 min 3 s 28', '2016-08-17', 'NULL', NULL'),
('1 h 18 min 46 s', '2012-08-04', 'NULL', NULL'),
('3 h 36 min 53 s', '2012-08-11', 'NULL', NULL'),
('8,90 m', '1968-10-18', 'NULL', NULL'),
('18,09 m', '1996-07-27', 'NULL', NULL'),
('2,39 m', '1996-07-28', 'NULL', NULL'),
('6,03 m', '2016-08-16', 'NULL', NULL'),
('23,30 m', '2021-08-05', 'NULL', NULL'),
('69,89 m', '2004-08-23', 'NULL', NULL'),
('84,80 m', '1988-09-26', 'NULL', NULL'),
('90,57 m', '2008-08-23', 'NULL', NULL'),
('9018 points', '2021-08-05', 'NULL', NULL'),
('10 s 61', '2021-07-31', 'NULL', NULL'),
('21 s 34', '1988-09-29', 'NULL', NULL'),
('48 s 25', '1996-07-29', 'NULL', NULL'),
('1 min 53 s 43', '1980-07-27', 'NULL', NULL'),
('3 min 53 s 11', '2021-08-06', 'NULL', NULL'),
('14 min 26 s 17', '2016-08-19', 'NULL', NULL'),
('29 min 17 s 45', '2016-08-12', 'NULL', NULL'),
('2 h 23 min 07', '2012-08-05', 'NULL', NULL'),
('12 s 26', '2021-08-00', 'NULL', NULL'),
('51 s 46', '2021-08-04', 'NULL', NULL'),
('8 min 58 s 81', '2008-08-16', 'NULL', NULL'),
('1 h 25 min 16 s', '2012-08-11', 'NULL', NULL'),
('7,40 m', '1988-09-29', 'NULL', NULL'),
('15,67 m', '2021-08-00', 'NULL', NULL'),
('2,06 m', '2004-08-28', 'NULL', NULL'),
('5,05 m', '2008-08-18', 'NULL', NULL'),
('22,41 m', '1980-07-24', 'NULL', NULL'),
('72,30 m', '1988-09-29', 'NULL', NULL'),
('82,29 m', '2016-08-15', 'NULL', NULL'),
('71,53 m', '2004-08-27', 'NULL', NULL'),
('7291 points', '1988-09-24', 'NULL', NULL'),
('21 s 07', '2021-08-00', 'NULL', NULL'),
('47 s 02', '2021-07-29', 'NULL', NULL'),
('1 min 42 s 96', '2008-08-12', 'NULL', NULL'),
('3 min 40 s 14', '2012-07-28', 'NULL', NULL'),
('7 min 41 s 28', '2021-07-27', 'NULL', NULL'),
('14 min 31 s 02', '2012-08-04', 'NULL', NULL'),
('51 s 85', '2016-08-13', 'NULL', NULL'),
('1 min 53 s 28', '2021-07-30', 'NULL', NULL'),
('57 s 13', '2016-08-07', 'NULL', NULL'),
('2 min 06 s 38', '2021-07-29', 'NULL', NULL'),
('49 s 45', '2021-07-31', 'NULL', NULL'),
('1 min 51 s 25', '2021-07-28', 'NULL', NULL'),
('1 min 54 s 23', '2008-08-15', 'NULL', NULL'),
('4 min 03 s 84', '2008-08-10', 'NULL', NULL'),
('23 s 81', '2021-08-00', 'NULL', NULL'),
('51 s 96', '2021-07-30', 'NULL', NULL'),
('1 min 53 s 50', '2021-07-28', 'NULL', NULL'),
('3 min 56 s 46', '2016-08-07', 'NULL', NULL'),
('8 min 4 s 79', '2016-08-12', 'NULL', NULL'),
('15 min 35 s 35', '2021-07-26', 'NULL', NULL'),
('57 s 47', '2021-07-27', 'NULL', NULL'),
('2 min 4 s 06', '2012-08-03', 'NULL', NULL'),
('1 min 4 s 93', '2016-08-08', 'NULL', NULL'),
('2 min 18 s 95', '2021-07-30', 'NULL', NULL'),
('55 s 48', '2016-08-07', 'NULL', NULL'),
('2 min 3 s 86', '2021-07-29', 'NULL', NULL'),
('2 min 6 s 58', '2016-08-09', 'NULL', NULL'),
('4 min 26 s 36', '2016-08-06', 'NULL', NULL');
INSERT INTO Date_calendar (date_cal, medal_ceremony_date_cal) VALUES
('2024-07-26', False),
('2024-07-27', True),
('2024-07-28', True),
('2024-07-29', True),
('2024-07-30', True),
('2024-07-31', True),
('2024-08-01', True),
('2024-08-02', True),
('2024-08-03', True),
('2024-08-04', True),
('2024-08-05', True),
('2024-08-06', True),
('2024-08-07', True),
('2024-08-08', True),
('2024-08-09', True),
('2024-08-10', True),
('2024-08-11', True);